### PR TITLE
Updating 18F Consulting copy

### PR DESCRIPTION
**Pull request by blacktm**
Updating our content on the /consulting page.

### CODE REVIEW

**Comment by gboone** [comment]
I defer to @awfrancisco for this.

**Comment by cscairns** [comment]
Wait, don't merge this yet. This isn't the correct copy.

**Comment by cscairns** [comment]
now it's good

**Comment by cscairns** [comment]
@gboone @awfrancisco: we good to merge this?

cc @blacktm

**Comment by blacktm** [comment]
@cscairns It's going through comms now.

**Comment by awfrancisco** [comment]
@cscairns @blacktm I've updated the content to move the call to action and to remove the bios for now. I removed the bios so we are not duplicating content on the team page and also so /consulting is consistent with other internal pages. In the next iteration we will add a link to the team page sorted just for consulting. There may be other design ways to get the team on /consulting as well.

I'm going to pass this by @OriHoffer now and then we will move to get it on the site.

**Comment by OriHoffer** [comment]
Looks good from my side. Back to you @awfrancisco

**Pull request merged**
