### PR TITLE
Publishing Acquisition Technical Lead positions

### PR DESCRIPTION
**Pull request by elainekamlley**
[CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/acq-tech-lead)

[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/acq-tech-lead/join/)

Changes proposed in this pull request:
- Adding open acq tech lead positions
- Fixed line breaks in gov resume sample

/cc @awfrancisco @hestherchang

### CODE REVIEW

**Comment by hestherchang** [comment]
@elainekamlley should I be able to see the preview? I get a 404 when i click the link

**Comment by elainekamlley** [comment]
@hestherchang try it now. Takes a minute for it to load

**Comment by hestherchang** [comment]
It's taking me to a page where I can see blog posts and 'get in touch'. Should I be looking somewhere specific on this page? @elainekamlley

**Comment by awfrancisco** [comment]
Looks good to me. 

@hestherchang you can see them here https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/acq-tech-lead/join/acquisition-technical-lead-gs14/
https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/acq-tech-lead/join/acquisition-technical-lead-gs15/

**Comment by hestherchang** [comment]
thank you! looks good to me too

**Pull request merged**
