### PR TITLE
Hire page redesign

### PR DESCRIPTION
**Pull request by gemfarmer**
Fixes issue(s) #1891 

[CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/newsletter)

[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/newsletter/contact/)

Changes proposed in this pull request:
- starts redesign of hire page, adding a new flow for the newsletter

Outreach team, how can I get access to the MailChimp account so that I can update the redirect? Right now it redirects to `/thank-you/`, which works great, but will need to change if we are using an in-page sign up confirmation. 

/cc @awfrancisco @gboone @elainekamlley @austinhernandez

### CODE REVIEW

**Comment by awfrancisco** [comment]
@gemfarmer Instructions to get access to MailChimp are [here](https://handbook.18f.gov/mailchimp/). If it's easy to do, we can also pair and you can walk me through the steps rather than you signing up for a new account.

**Comment by coreycaitlin** [comment]
@gemfarmer let's bring this inline with the layout/design adjustments we made for the project page template. And we should figure out whether we want to rename to "Contact".

**Comment by gemfarmer** [comment]
> @gemfarmer let's bring this inline with the layout/design adjustments we made for the project page template.

Which layout adjustments specifically?

> And we should figure out whether we want to rename to "Contact".

💯*10^💯  votes for "Contact"

**Comment by gemfarmer** [comment]
This could use a final review @coreycaitlin & @austinhernandez! I can squash and merge once the approvals come rolling in

**Comment by coreycaitlin** [comment]
@gemfarmer made a couple of tiny edits to the hierarchy in the right-hand column so it's a little clearer what's related to what.

**Pull request merged**
