### PR TITLE
Add post for Oracle databases (blog-drafts #873)

### PR DESCRIPTION
**Pull request by beechnut**
# Pull request summary
Adds blog post for https://github.com/18F/blog-drafts/issues/873

> [!IMPORTANT]
> This pull request should only be merged AFTER #3957 is merged. This post will not look good otherwise.

### CODE REVIEW

**Comment by alexsobledotgov** [comment]
Preview link not working for me -- am I looking in the wrong place? https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.sites.pages.cloud.gov/preview/18f/18f.gsa.gov/beechnut/oracle-dbs/

**Comment by alexsobledotgov** [comment]
Getting a 404 Page not found

**Comment by beechnut** [comment]
Preview build here: https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.sites.pages.cloud.gov/preview/18f/18f.gsa.gov/beechnut/oracle-dbs/2024/07/09/working-with-oracle-databases-in-open-source-projects/

**Comment by beechnut** [comment]
@bpdesigns @edwintorres This is ready to publish!

Sorry for bringing this up after sprint planning — I didn't realize the steps had changed since I started the publication process, so I didn't know I had to add this to the TLC board until very recently. Let me know what you need from me on this, and once we have a publication date I can update the PR to match.

**Review by bpdesigns — APPROVED** [review]

**Comment by beechnut** [comment]
Thanks @bpdesigns! I'm going to change the date on the file to today's date, then merge.

**Pull request merged**
