### PR TITLE
Use pa11y to test homepage

### PR DESCRIPTION
**Pull request by adelevie**
Ignore this for now. I'm testing out how we can have some automated accessibility testing for the site.

### CODE REVIEW

**Comment by gboone** [comment]
would this make #566 obsolete?

**Comment by adelevie** [comment]
I'll just say that #566 is obsolete. Blast it away!

**Comment by gboone** [comment]
:boom:

**Comment by konklone** [comment]
Curious the state of this, and of pa11y?

**Comment by gboone** [comment]
I was about to say the same thing.

**Comment by gboone** [comment]
We still want to do this; there was a good discussion in Slack about how we might do it, and how we might use the results effectively. We'd also have to re-open this against `master` so that we're testing the new site. Closing for now.

**Pull request closed without merging**
