### PR TITLE
Add 'tax court' tag to blog posts

### PR DESCRIPTION
**Pull request by mark-meyer**
# Pull request summary
This adds tax court tag to blog posts to allow them to show up in related posts under the project page

(Optional) Closes #(issue_number).

## Reminder - please do the following before assigning reviewer

- [ ] update readme
- [ ] For frontend changes, ensure design review

And make sure that automated checks are ok

- fix houndci feedback
- ensure tests pass
- federalist builds
- no new SNYK vulnerabilities are introdcued

### CODE REVIEW

**Comment by Dahianna** [comment]
@mark-meyer is tax court in the `tags `yml: https://github.com/18F/18f.gsa.gov/blob/main/tests/schema/tags.yml

**Comment by mark-meyer** [comment]
@Dahianna hmm, no it's not, I used it because it is the tag on https://github.com/18F/18f.gsa.gov/blob/main/_services_projects/tax-court.md 

Can I just add the tag to `tags.yml`, or is there another process for adding tags to this schema?

**Comment by Dahianna** [comment]
Yep, feel free to add it. I believe the project page tags and the blog tags
are in different locations, but they both show up during a search.


U.S. General Services Administration

*Dahianna V. Salazar Foreman*
 Digital Marketing
 TTS Outreach
 Technology Transformation Services
 Federal Acquisition Service
  <https://www.linkedin.com/company/gsa-tts/>  <https://twitter.com/GSA_TTS>

**Comment by mark-meyer** [comment]
Okay, done! Thanks @Dahianna.

**Review by Dahianna — APPROVED** [review]

**Pull request merged**
