### PR TITLE
More deploy script fixes, edits to Micah's name

### PR DESCRIPTION
**Pull request by gboone**
Deploys #821 and #820 to production

### CODE REVIEW

**Comment by gboone** [comment]
I swear I know how to spell. Moar :coffee:??

**Comment by gboone** [comment]
This PR now also deploys the web font changes introduced in #805, @konklone can provide context if there are any questions. TL;DR; WOFF2 fonts load more efficiently over HSTS enabled browsers.

**Comment by konklone** [comment]
> TL;DR; WOFF2 fonts load more efficiently over HSTS enabled browsers.

SPDY-enabled browsers. (Or HTTP/2 enabled browsers, but we don't support HTTP/2 on our server at this time.)

**Comment by gboone** [comment]
Derp. That's what I meant. HSTS isn't a browser thing. Thanks @konklone.

**Pull request merged**
