### PR TITLE
Integrate jekyll_pages_api_search

### PR DESCRIPTION
**Pull request by mbland**
This still needs a bit of tweaking, to get the search box in the right place and looking right everywhere, but it works. Ensuring every page has the proper title and content headings will improve the quality of results.

@gboone I'm happy to jam on this in-person sometime; you should also feel free to push commits directly to this branch.

cc: @afeld

### CODE REVIEW

**Comment by afeld** [comment]
:+1:

**Comment by gboone** [comment]
Thanks for getting this started, @mbland. cc: @elainekamlley

**Comment by mbland** [comment]
This just crossed my mind... Any interest in getting it hooked up anytime soon?

**Comment by mbland** [comment]
Ping... Still needs styling love and to be added to the layouts that need it, but still works.

**Comment by gboone** [comment]
This is obsolete with the coming redesign. We're using the search!

**Pull request closed without merging**
