### PR TITLE
prices

### PR DESCRIPTION
**Pull request by lauraGgit**
Fixes issue(s) # .

[CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/BRANCH_NAME)

[:sunglasses: PREVIEW](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.app.cloud.gov/preview/18f/18f.gsa.gov/BRANCH_NAME/)

[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/BRANCH_NAME/README.md)

Changes proposed in this pull request:
-
-
-

Checklist:
- [ ] All images being added have been optimized **_--> [learn more](https://18f.gsa.gov/styleguide/images) about how to optimize images <--_**

/cc @relevant-people

### CODE REVIEW

**Comment by hannahkane** [comment]
I can't see the Preview - is there something I need to do to make that work?

I gather from the commit we're removing the references to pricing? +1 on that.

**Comment by hannahkane** [comment]
Can we remove this sentence at the end? "Prices are current as of June 30, 2020"

Otherwise, LGTM!

**Review by hannahkane — CHANGES_REQUESTED** [review]
Remove sentence about pricing at bottom. Otherwise, +1.

**Comment by lauraGgit** [comment]
@hannahkane good for re-review

**Review by hannahkane — APPROVED** [review]
+1

**Pull request merged**
