### PR TITLE
Add acquisition to how we work

### PR DESCRIPTION
**Pull request by Dahianna**
Fixes issue(s) #3101

[CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/acquisition-offerings)

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/acquisition-offerings/)

[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/acquisition-offerings/README.md)

Changes proposed in this pull request:
- Add acquisition offerings to "How we work"

### CODE REVIEW

**Comment by cmajel** [comment]
@Dahianna I took a look and fixed a few things:

[Updated preview link](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/18f.gsa.gov/acquisition-offerings/how-we-work/)

* I fixed some missing HTML tags that was messing with the layout and causing the icons to sit under the section. 

* I adjusted some of the CSS so that `Acquisitions Services` appears as a heading to the items that follow and to evenly space the sections. 

* I adjusted the `capture` variable names so that they were unique to each section and easier to follow in the code. 

* I noticed that we were using empty named anchors like `<a name="path-analysis"></a>` to create [anchor links to jump to a section like this](https://18f.gsa.gov/how-we-work/#experiment-iterate). This caused the icons and section text to be misaligned. I switched these to `ids` on the parent section, which removes the space and I believe [follows the HTML5 spec a bit better](https://stackoverflow.com/questions/484719/should-i-make-html-anchors-with-name-or-id). 

A suggestion - it seems a bit unbalanced to have an into and explanation for `Acquisitions Services, but not for PAs and E&Is. Perhaps there should be a `Problem definition services` that intros PAs and E&Is? Something like...

Title:
* Problem definition services
* Defining the problem

Body: 
- something about how we work with teams to provide a honest assessment and recommendation
- something about how you get the expertise of experienced designers, developers, product managers and acquisition leads

**Comment by Dahianna** [comment]
Hi @AshleyO85 and @saraheckert Here's the preview for the how we work page with the Acquisitions content. I did some tweaking of the content to provide a fit the current page template and provide better user experience. I can always make changes, so feel free to make suggestions.
https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/18f.gsa.gov/acquisition-offerings/how-we-work/

**Comment by saraheckert** [comment]
I think that amounts may be off, I think we had assisted acq starting at 750K; that was the only change I saw

**Comment by Dahianna** [comment]
> A suggestion - it seems a bit unbalanced to have an into and explanation for `Acquisitions Services`, but not for PAs and E&Is. Perhaps there should be a `Problem definition services` that intros PAs and E&Is? Something like...
> 
> Title:
> 
> * Problem definition services
> * Defining the problem
> 
> Body:
> 
> * something about how we work with teams to provide a honest assessment and recommendation
> * something about how you get the expertise of experienced designers, developers, product managers and acquisition leads

@cmajel Thank you for your help! I'll bring your suggestions to leadership so we can include them on the next iteration.

**Comment by saraheckert** [comment]
I think that suggestion is great @Dahianna, lets definitely incorporate that in our next release when we make edits to the PA and E&I sections

**Pull request merged**
