### PR TITLE
"READMEs for you and me" blog post

### PR DESCRIPTION
**Pull request by alexsoble**
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/BRANCH_NAME/README.md)

Changes proposed in this pull request:

- Add blog post: "READMEs for you and me" 

Checklist:
- [ ] All images being added have been optimized 

/cc @Dahianna

### CODE REVIEW

**Comment by alexsoble** [comment]
I'd like to aim to publish on 3/3. Hoping that's enough time to line up a nice header image.

**Comment by alexsoble** [comment]
Hoping for a 3/4 or 3/5 pub date — @Dahianna, let's discuss on Monday. Thanks!

**Comment by Dahianna** [comment]
It's scheduled to publish tomorrow, do you want me to move it to Thursday?

**Comment by alexsoble** [comment]
@Dahianna — Yes, I would love if we could move the scheduled pub date to this Thursday 3/5. Thank you so much!

**Comment by Dahianna** [comment]
Done!

**Comment by alexsoble** [comment]
@Dahianna Wonderful, thank you so much! Will update the PR accordingly.

**Comment by Dahianna** [comment]
@alexsoble If there are no more changes, I can go ahead and merger

**Comment by alexsoble** [comment]
@Dahianna Yep, good to go on my end — thank you for checking!

**Pull request merged**
