### PR TITLE
Hatch Act link was 404'd, suggested replacement

### PR DESCRIPTION
**Pull request by oghaffari**
I wish there was a clean URL like the original one, but that didn't work and I couldn't figure out exactly how to get it to work, so I am suggesting a link that I know works.

### CODE REVIEW

**Comment by gboone** [comment]
@oghaffari can you change the target branch of this PR to `master`? (Don't know if that's possible from a fork. LMK here if you can't.)

**Comment by oghaffari** [comment]
@gboone Done! Let me know if that works or if you need anything else. I am getting a 1 failed (ci/circleci - No test commands were found) and 1 pending check (continuous-integration/travis-ci/pr - The Travis CI build is in progres), FYI. I'm pretty sure you can see that, but letting you know just in case.

**Comment by oghaffari** [comment]
Here's to hoping that didn't mess anything up - I suddenly got a notification saying I'm trying to merge 766 commits... I'm only a message away if I can do anything to help!

**Comment by gboone** [comment]
Oh boy, yeah, I should have anticipated that… hmm, I'll figure out how to get your contribution in.

**Comment by gboone** [comment]
OK, I cherry-picked the commit into the branch. You _should_ be a contributor now. Thanks again!

**Pull request closed without merging**
