### PR TITLE
Adding new thumbnail to the site

### PR DESCRIPTION
**Pull request by jeanninehunter**
adding a new thumbnail to the website

### CODE REVIEW

**Comment by konklone** [comment]
@jeanninehunter So you know, the image looks a bit squashed:

jeannine

Is it possible to re-cut it at the original aspect ratio? Happy to help if you want to send the original over on Slack or something.

**Comment by jeanninehunter** [comment]
Thanks @konklone for reaching out to me; I smooshed the previous image, and just uploaded the original in Slack.

**Comment by jeanninehunter** [comment]
Thanks @konklone! I iadvertenly smooshed that mug; just uploaded the original to you in Slack.

**Comment by konklone** [comment]
Here's a 250x250 version:

jhunter-250

And here's a 1200x1200 version for safekeeping (in case we increase the size later):

jhunter-1200

**Pull request merged**
