### PR TITLE
Fixissue 3290

### PR DESCRIPTION
**Pull request by edwintorres**
Fixes issue(s) #3290.

[CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/fixissue-3290)

[:sunglasses: PREVIEW](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.app.cloud.gov/preview/18f/18f.gsa.gov/fixissue-3290/)

[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/fixissue-3290/README.md)

Changes proposed in this pull request:
-
-
-

Checklist:
- [x] All images being added have been optimized **_--> [learn more](https://18f.gsa.gov/styleguide/images) about how to optimize images <--_**

/cc @relevant-people

### CODE REVIEW

**Comment by igorkorenfeld** [comment]
@edwintorres could you post a federalist preview link for this?

**Comment by edwintorres** [comment]
> @edwintorres could you post a federalist preview link for this?

Do I need a Federalist account? I have to configure one.

**Comment by igorkorenfeld** [comment]
You would need to request one. But no worries, I'll try to pull it down locally.

**Comment by igorkorenfeld** [comment]
@Dahianna this looks good to me!

**Review by igorkorenfeld — APPROVED** [review]

**Comment by igorkorenfeld** [comment]
Based on #3317, we may actually want to hold off on merging this in since that autoprefixer gem will hopefully prevent future issues.

**Comment by apburnes** [comment]
Thanks @edwintorres for the PR! We are starting to transition our dependencies from being stored in git to using NPM and `jekyll-assets` and I've got a PR #3316 for pulling in USWDS.  Once #3316 is merged, we may be able to update this PR using the autoprefixer plugin based on issue #3317.  How does that sound?

**Comment by edwintorres** [comment]
Sound good to me. Thank you! I learn a lot working on this issue.

**Comment by apburnes** [comment]
Now that PR #3316 is merged and USWDS is being consumed via jekyl-assetss. This PR could be altered to use the autoprefixer plugin based on issue #3317.

**Comment by apburnes** [comment]
Closed by #3336

**Pull request closed without merging**
