### PR TITLE
Freezes redcarpet at v 3.2.3

### PR DESCRIPTION
**Pull request by gboone**
@konklone will this ensure we don't accidentally upgrade recarpet again?

### CODE REVIEW

**Comment by konklone** [comment]
Should, but we have a Travis error.

**Comment by gboone** [comment]
Yeah, and it's the same one we had before...

**Comment by gboone** [comment]
Wahoo, thanks Travis!

**Comment by monfresh** [comment]
What was the reasoning behind locking the version? redcarpet 3.2.3 has a known security vulnerability. I went through the git history but none of the commit messages explained why these changes were made.

**Comment by konklone** [comment]
As I recall, there was a regression of some sort when it upgraded from 3.2.3 to 3.3.0, but I can't find any details of what the regression was. It didn't come up because of a security vulnerability notification, and it would be worth us getting notices in place via [Gemnasium](https://gemnasium.com/) or something similar to avoid this going forward.

**Comment by monfresh** [comment]
I have a Gemnasium alert. That's how I ended up here :) I was planning on upgrading redcarpet but saw that it was locked and couldn't find any documentation in the Git history. Is it safe to assume that the test suite is robust enough to catch any issues if the new version is incompatible?

**Comment by gboone** [comment]
I recently tried updating this again and didn't make much progress. Any newer version of redcarpet with our current version of ruby fails to build. I think upgrading redcarpet might involve moving to a newer version of ruby.

**Comment by gboone** [comment]
Well, whaddya know. I just tried updating redcarpet again and it seems to have worked. The only thing our test suite won't catch is any change to how redcarpet interprets markdown syntax. I'm going to open a pull request @monfresh and we can jam on that together?

**Comment by gboone** [comment]
See #1791

**Pull request merged**
