### PR TITLE
Figcaption option

### PR DESCRIPTION
**Pull request by gemfarmer**
Fixes issue(s) #2162 

[CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/images)

[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/images/2017/01/11/the-best-way-to-build-big-is-to-start-small/)

Changes proposed in this pull request:
- noodling on figcaption

/cc @austinhernandez

### CODE REVIEW

**Comment by gemfarmer** [comment]
Ready to squash and merge once the tests passs!

**Comment by coreycaitlin** [comment]
I'm going to pull down this branch and add a few captions so we have good spots to see it in action (and also so those images have captions, because they needed them)

**Comment by coreycaitlin** [comment]
It looks like hero images _without_ a figcaption are getting a tiny (and admittedly subtle) grey box in the corner:

screen shot 2017-02-07 at 11 57 06 am

I think in this instance, we don't want anything to show up at all.

**Comment by coreycaitlin** [comment]
Okay! I think I've fixed that visual bug and added some captions. Will update with a list of posts to look at after my meetings.

**Comment by austinhernandez** [comment]
@gemfarmer i don't see any figz from the [preview link](https://federalist.18f.gov/preview/18F/18f.gsa.gov/images/2017/01/11/the-best-way-to-build-big-is-to-start-small/)! is that something yr working on @coreycaitlin? just let me know when it's ready for the review.

**Comment by coreycaitlin** [comment]
For all your reviewing needs:

With captions:

- https://federalist.18f.gov/preview/18F/18f.gsa.gov/images/2016/12/12/connecting-culture-change-at-18F-and-PBS/
- https://federalist.18f.gov/preview/18F/18f.gsa.gov/images/2016/11/25/what-18f-is-thankful-for-this-thanksgiving/
- https://federalist.18f.gov/preview/18F/18f.gsa.gov/images/2016/11/17/leadership-innovation-california-child-welfare-services/
- https://federalist.18f.gov/preview/18F/18f.gsa.gov/images/2016/10/14/iterative-workplace-design-denver-federal-center/

Without captions:

- https://federalist.18f.gov/preview/18F/18f.gsa.gov/images/2016/11/22/a-vulnerability-disclosure-policy-for-the-technology-transformation-service/
- https://federalist.18f.gov/preview/18F/18f.gsa.gov/images/2016/10/25/three-small-steps-you-can-take-to-reboot-agile-in-your-organization/

**Comment by austinhernandez** [comment]
@gemfarmer @coreycaitlin this _looks_ good but do you think it would pass an accessibility test? how can i find that information out?

also - were the captions also going to apply to inline images as well?

**Comment by gemfarmer** [comment]
@austinhernandez, @coreycaitlin is assembling a list of images that have figcaptions. It sounded like she will be posting them soon

**Comment by coreycaitlin** [comment]
Our commenting order is a little wonky here...

- List of posts with hero images with/without figcaptions is [above](https://github.com/18F/18f.gsa.gov/pull/2265#issuecomment-278173102)
- I don't think we've implemented the inline design yet, so we should do that ([this post](https://federalist.18f.gov/preview/18F/18f.gsa.gov/images/2016/10/14/iterative-workplace-design-denver-federal-center/) is a good place to look for inline images)
- For accessibility, I'll check with a color-contrast tool

**Comment by coreycaitlin** [comment]
Hmm, @gemfarmer can we pair on this? It was working a minute ago but now it isn't. I think our various changes/rebases are getting scrambled.

**Comment by coreycaitlin** [comment]
@austinhernandez Just tested the contrast, and I think we're good! Also we added inline styling for figcaptions.

**Pull request merged**
