### PR TITLE
Db subsetter post

### PR DESCRIPTION
**Pull request by catherinedevlin**
Pull request to collect comments in... please don't actually merge it yet!

### CODE REVIEW

**Comment by catherinedevlin** [comment]
Finally got suggestions from Eric, Ori, and Aiden (at least roughly) incorporated

**Comment by konklone** [comment]
Awesome!! Did you make that sweater photo yourself??

I just updated the post a bit:

* Add an `image` field to the post's metadata, so it has an image when shared on Facebook/Twitter/Slack/etc.
* Added an `excerpt` field so that the whole thing doesn't show on the site homepage.
* Changed image links to be absolute, not relative (removed the `..`).
* Put the bash line in fenced backtick markdown syntax instead of indented, so as to put it into our normal pygments highlighting pipeline (even though there's no highlighting).
* Removed a stray backtick in front of `--schema`.
* Italicized _(cue inspiring music)_ for dramatic effect (and visual separation).

This still needs to go through the comms approval process, which typically starts over in [blog-drafts](https://github.com/18F/blog-drafts). @OriHoffer, since we're so far along here, mind doing the approval step here instead this time?

Here's a screenshot of the post as it appears now for me in development:

database testing

**Comment by OriHoffer** [comment]
Looks good to me, and I agree, I don't think this needs any additional review from Comms/Congressional. Check with @gboone on scheduling the post, since we have a couple others in the queue I think.

**Comment by OriHoffer** [comment]
Does this then need to get moved to blog-posts?

**Comment by gboone** [comment]
Nah, it's good here. The [Protosketching post went out this morning](https://18f.gsa.gov/2015/01/06/protosketch/) and so I'm thinking we publish tomorrow or Thursday.

**Comment by gboone** [comment]
Front matter checklist:
[x] title 
[ ] date
[x] layout: post
[x] tags
[x] authors
[x] image
[x] description
[x] excerpt

**Comment by catherinedevlin** [comment]
thanks, got the date added to the front matter...

On Tue, Jan 6, 2015 at 11:45 AM, Greg Boone <notifications@github.com>
wrote:

> Front matter checklist:
> [x] title
> [ ] date
> [x] layout: post
> [x] tags
> [x] authors
> [x] image
> [x] description
> [x] excerpt
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/18f.gsa.gov/pull/358#issuecomment-68891817>.
>



-- 
- Catherine
http://catherinedevlin.blogspot.com

**Comment by gboone** [comment]
Excellent, this will roll to staging.18f.us tomorrow morning for a quick preview before we deploying.

**Pull request merged**
