### PR TITLE
USWDS v2 update

### PR DESCRIPTION
**Pull request by apburnes**
## Description

Updating from v1 to v2 of uswds design system.

[:sunglasses: PREVIEW](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.app.cloud.gov/preview/18f/18f.gsa.gov/update-uswds/)

Changes proposed in this pull request:
- Update from uswds v1.x to v2 

### Sidenav (Pages: about, contact...)
- [x] Fix mobile view to show side nav as a sticky accordian

### Search Page
- [x] Change button color to be more accessible

### How We Work

- [ ] Where's acquisitions?

### Blog
- [x] Mobile View: Add previous and next page navigators to be right after las post on page.

All same issues for mobile

### Guides

- [x] Update content layout width and spacing

### Footer

- [x] Implement new footer

### CODE REVIEW

**Comment by heymatthenry** [comment]
The v2 grid is in place on most pages, I think the next priority ought to be the font sizing since that'll make it clearer what's left to fix.

**Comment by apburnes** [comment]
It's starting to come together 👍👍

@heymatthenry let's find sometime this week to touch base.

**Comment by apburnes** [comment]
## To Do

- SASS errors when compiling
- Work on font sizing
- Updating the new design

## Roadmap

- [ ] SASS errors when compiling @heymatthenry 
- Reviewing higher level components that can plug and play from V2 into 18f.gsa.gov
  - [ ] Identify possible adhoc custom code / components @apburnes 
  - [ ] Identify any current repetition/duplication in UI components @apburnes 
  - [ ] Map adhoc to USWDS v2 @apburnes 
  - [ ] Scrub/remove adhoc custom code / components *tbd - reassess next sprint*
- [ ] Add updated `home.html`

**Comment by apburnes** [comment]
Continuing _To Do_ list  #3103

**Comment by Dahianna** [comment]
I updated the checklist based on the work we've done, feel free to update it if there was anything I missed. I did noticed the project page template is all kinds of wrong, so probably we should concentrate on it next. Let me know what you think? @Artahlil @apburnes  https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.app.cloud.gov/preview/18f/18f.gsa.gov/update-uswds/what-we-deliver/forest-service/

**Comment by Dahianna** [comment]
@apburnes to look at conflicts

**Comment by Dahianna** [comment]
Fix how we work page: https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.app.cloud.gov/preview/18f/18f.gsa.gov/update-uswds/how-we-work/

**Pull request merged**
