### PR TITLE
Dev --> master

### PR DESCRIPTION
**Pull request by gemfarmer**
Fixes issue(s) #2140, #2103, #2105, #2143, #2012

[CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/dev)

[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/dev/)

Changes proposed in this pull request:
- replaced `redcarpet` with the [`kramdown`](https://kramdown.gettalong.org/) markdown renderer. This was to fix how blockquotes are rendered #2140 
- Updated blockquotes and added a `.pquote` pull quote style #2146 
- Added clearer hover styles to homepage links and cards #2103 
- Started a styleguide that lives at `/styleguide/` #2095 
- Prototype `/our-work/` page #2150 
- Adds `rspec` ruby testing framework. Wrote some tests for ruby plugins #2153 
- updated CONTRIBUTING.md text for filing pull requests
- markdown clean up https://github.com/18F/18f.gsa.gov/pull/2163/commits/642ea9bf810f631641d8f81bd28b2123800e943f
- lots of fixes to old blog posts, including removing hero images for pixelated/duplicate images
- adds a codeclimate config #2157  

/cc @coreycaitlin @austinhernandez @elainekamlley

### CODE REVIEW

**Comment by coreycaitlin** [comment]
Need to check YouTube embeds, ala [this post](https://federalist.18f.gov/preview/18F/18f.gsa.gov/dev/2014/12/15/going-to-gov-college/)

**Comment by coreycaitlin** [comment]
also this one https://federalist.18f.gov/preview/18F/18f.gsa.gov/dev/2015/12/30/turning-learning-up-to-11/

**Comment by coreycaitlin** [comment]
and this one https://federalist.18f.gov/preview/18F/18f.gsa.gov/dev/2015/11/13/answering-common-questions-about-cloud-gov/

**Comment by coreycaitlin** [comment]
broken markdown link here: https://federalist.18f.gov/preview/18F/18f.gsa.gov/dev/2016/09/27/pro-tips-for-data-friendly-regulations-proposals/

**Comment by coreycaitlin** [comment]
stray `<br>` tag here https://federalist.18f.gov/preview/18F/18f.gsa.gov/dev/2016/08/08/facts-about-publishing-open-source-code-in-government/

**Comment by gemfarmer** [comment]
💥

**Pull request merged**
