### PR TITLE
Update heading levels for oracle blog post

### PR DESCRIPTION
**Pull request by igorkorenfeld**
# Pull request summary
This PR shifts the headings in the databases blog post down one level, so that there is only a single `h1` headings on the page. Our blog uses the post title as an `h1`, so I've shifted every other heading by 1 (`h1`-> `h2`, `h2`->`h3`, etc...). The exception to this this was the last two headings for the Conclusion and Special Thanks, which seemed like they were not part of the "Tutorial Part 2" section, but if that's incorrect happy to adjust. 

## Reminder - please do the following before assigning reviewer

- [ ] Update readme
- [ ] For frontend changes, ensure design review
- [ ] For content changes beyond typos, add Ron Bronson as a reviewer

### CODE REVIEW

**Review by beechnut — CHANGES_REQUESTED** [review]
First of all, thanks for noticing this. Since this is a site-wide rule that's not listed anywhere as far as I can tell, we should build this check in to the site itself — I've added this to the [18F replatforming post-migration tasks]().

I don't like the way the h4's look in the preview build — when scanning, they almost read as body text, and don't break the content up visually very well.

I think I'd significantly prefer knocking just the h1s down to h2s and leaving the rest as-is. It may not be as semantically correct, but having them stay larger better fulfills their purpose as separators.

**Comment by igorkorenfeld** [comment]
Great, I've noticed the issue on a number of blog posts, so that'll be a good upgrade.  

A possible alternative which would keep the semantic structure would be to style the `h4` and `h5` a bit larger in the blog posts?

**Comment by cantsin** [comment]
We can have our cake and eat it too -- we can have semantically correct headers and sizes to match, but maybe this is a separate (a11y related?) ticket.

**Comment by igorkorenfeld** [comment]
@beechnut I've update the styling for the headings to give the `h4`s and `h5`s a bit more prominence. The added benefit is that this better matches our intended design from last year too :) 

Let me know how this looks to you

**Review by beechnut — APPROVED** [review]

**Comment by beechnut** [comment]
Wow, this looks great! Love the new styling! Approved!

**Pull request merged**
