### PR TITLE
Replaced text with approved revised CoC

### PR DESCRIPTION
**Pull request by jeanninehunter**
Replaced text with approved revised CoC

Fixes issue(s) # .

[CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/jeanninehunter-patch-1)

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/jeanninehunter-patch-1/)

[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/jeanninehunter-patch-1/README.md)

/cc @elainekamlley

### CODE REVIEW

**Comment by jeanninehunter** [comment]
Thx @awfrancisco for reconciling the formatting!

**Comment by elainekamlley** [comment]
This looks good! I'm gonna adjust the layout a bit before merging

**Comment by jeanninehunter** [comment]
Thx @elainekamlley for fixing the formatting!

**Comment by elainekamlley** [comment]
Replaced header links with a subnav. LGTM!

**Comment by awfrancisco** [comment]
Do we need the version dates at the bottom?

**Comment by jeanninehunter** [comment]
We could remove that info (it appears in the original repo), @awfrancisco

**Pull request merged**
