### PR TITLE
Fixit day sprint

### PR DESCRIPTION
**Pull request by gboone**
- upgrades to Jekyll 3.0 (_finally_)
- adds gems appropriate for Jekyll 3.0 (which seems a little more verbose about missing gems, probably a good thing)
- updates data from the public version of the hub
- fixes humans.txt for Jekyll 3.0

### CODE REVIEW

**Comment by konklone** [comment]
A note on Jekyll 3 -- I found bugs with `--watch` mode under Jekyll 3's new default of partial rebuilds.

**Comment by gboone** [comment]
Oh, good catch. I think there's a way to force full rebuilds, if not will disable rebuilding by default.

**Comment by gboone** [comment]
Okay, updated to force a full rebuild by default. If we have trouble with that we can completely disable it until the next version of Jekyll (beta or no) comes out.

**Comment by gboone** [comment]
@konklone this look good now? Feel free to merge if :+1:

**Comment by konklone** [comment]
:+1:

**Pull request merged**
