### PR TITLE
Fix a Typo

### PR DESCRIPTION
**Pull request by zeke**
:wave: Just perusing the blog and noticed a typo.

`s/built first iteration/built the first iteration/`

Is `staging` the right target branch for PRs?

### CODE REVIEW

**Comment by fureigh** [comment]
Thanks, @zeke! `staging` should be the right target branch for PRs, according to the README, though it appears this branch needs to be updated to incorporate the latest changes. Can you rebase and push again so your commit comes through without the 55 others?

**Comment by zeke** [comment]
Hey @fureigh it looks like GitHub now has an "Update Branch" button!

screen shot 2015-10-20 at 9 14 39 pm

I clicked it and it worked, but it created a merge commit (https://github.com/18F/18f.gsa.gov/commit/003dbb0d3dc553bd1e73fed291fa72a123ccac9b). Hmm. Let me know if I should just close this PR and start another.

**Comment by zeke** [comment]
Rebased. Ready to :ship:

**Comment by gboone** [comment]
Thanks @zeke

**Comment by fureigh** [comment]
Thanks, @zeke!

**Pull request merged**
