### PR TITLE
Update homepage, start styleguide

### PR DESCRIPTION
**Pull request by gemfarmer**
Fixes issue(s) #1952 

[CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/homepage-update)

[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/homepage-update/)
[:sunglasses: PREVIEW styleguide](https://federalist.18f.gov/preview/18F/18f.gsa.gov/homepage-update/styleguide/)

Changes proposed in this pull request:
- Homepage redesign - [invision homepage](https://projects.invisionapp.com/share/3X9J87M4V#/screens/209522573_Home_Mvp)
- Start styleguide - [invision styleguide](https://projects.invisionapp.com/share/3X9J87M4V#/screens/209057303)
- remove deprecated `_cards` collection

/cc @coreycaitlin @austinhernandez

### CODE REVIEW

**Comment by gemfarmer** [comment]
@austinhernandez homepage and styleguide primordial oozings ready for you to look at! You can follow the preview links above.

For the styleguide, please don't hold back with the feedback. It would be better to restructure things now (if need be) than wait til later!

**Comment by gemfarmer** [comment]
@austinhernandez does this need cleaning up at all, or is this ready for merging?

**Comment by coreycaitlin** [comment]
@gemfarmer Let's keep this on a separate branch until we share it a little more widely and maybe get a tiny bit of testing, since it changes the homepage so much.

**Comment by austinhernandez** [comment]
@gemfarmer i'd like to reduce some of the padding around the hero and let's work together section. (removte the top & bottom margin in .content-focus)

**Comment by gemfarmer** [comment]
`.content-focus` is used in other pages. Do we want to reduce the padding in those other pages, too?

**Comment by gemfarmer** [comment]
@austinhernandez per our conversation yesterday, this PR contains _only_ the basic suite of changes to the homepage, not other style tweaks and hover state changes. I have made another PR here (#2131) that contains those changes!

Merge if you feel it has met the basic qualifications for the homepage redesign. We can attend to smaller problems in that follow up PR!

**Comment by gemfarmer** [comment]
@austinhernandez and I separated the "controversial" changes from the acceptable changes to the homepage. After merging this to `dev`, we are going to start making a new `project-pages` that contains these changes, as well as the unmerged "controversial" changes. That branch can exist as a repository for updates that won't immediately make it into `dev`, such as layouts that consolidate and reference project pages.

**Pull request merged**
