### PR TITLE
de-duplicate entries in GS-15 Evaluation section

### PR DESCRIPTION
**Pull request by mirrorstage**
Fixes issue(s) # .

[CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/BRANCH_NAME)

[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/BRANCH_NAME/)

[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/BRANCH_NAME/README.md)

Changes proposed in this pull request:
- Entries 2-5 in GS-15 Evaluation section (describing competencies/KSAs in "technology solutions" and "oral communication") are duplicative and/or present competing versions of these c/KSAs with slight differences.

/cc @relevant-people

### CODE REVIEW

**Comment by gemfarmer** [comment]
cc @hestherchang @gboone

**Comment by gemfarmer** [comment]
Thanks for your @mirrorstage. I will get your changes in front of the pertinent people and we will get back to you!

**Comment by mirrorstage** [comment]
My pleasure, @gemfarmer!

-Dave

**Comment by wslack** [comment]
Hi @mirrorstage - thank you for submitting the PR! I think I mentioned on twitter that I suspected some of the language was not entirely under 18F's sole control and it turns out that that's true when it comes to job postings. For that reason, this particular PR probably can't be accepted without a lot of consultations (someone else can confirm), but I want to say a heart felt **thank you** for jumping in and contributing! It makes us 😀 to see PRs.

**Comment by hestherchang** [comment]
@mirrorstage Thank you so much for this PR. What Will shared is exactly correct. We work with our partners, GSA HR, to make sure we have all of the necessary information on every job posting and sometimes that means information is duplicated. Thank you for bringing this to our attention and for being an active part of our community!

**Comment by mirrorstage** [comment]
Hi, @wslack and @hestherchang  -- Thanks for the follow-up! I understand completely. To borrow the language of that section of the posting, I'm familiar with "complex or bureaucratic environments."

**Pull request closed without merging**
