### PR TITLE
Updates to /Developer page

### PR DESCRIPTION
**Pull request by gbinal**

### CODE REVIEW

**Comment by gbinal** [comment]
To consider:  
* [ ] Discovery
* [ ] MyUSA
* [ ] FOIA
* [ ] FEC
* [ ] api.data.gov api 
* [ ] Midas
* [ ] Hub
* [ ] Calc

**Comment by LindsayYoung** [comment]
:+1: LGTM

**Comment by gbinal** [comment]
To Update - all, please don't merge yet.  This PR is a work in progress.

**Comment by gbinal** [comment]
Am also asking around to see if any of these projects have resulted in APIs or datasets:  
* https://github.com/18F/jekyll-search-server
* https://github.com/18F/beckley
* https://github.com/18F/bronto-api
* https://github.com/18F/answers-ruby-client
* https://github.com/18F/MicroP3ApiUser
* https://github.com/18F/PriceHistoryAPI
* https://github.com/18F/team-api
* https://github.com/18F/r2s
* https://github.com/18F/ekip-api
* https://github.com/18F/domain-scan
* https://github.com/18F/notalone
* https://github.com/18F/letgirlslearn
* https://github.com/18F/jekyll_pages_api

**Comment by gbinal** [comment]
Okay - this is pretty caught up so.  The relevant teams have all been notified and, barring comlaints, I'll plan to merge COB today.

**Comment by gbinal** [comment]
Leaving off MyUSA for now.

**Comment by gboone** [comment]
Is this good to go then?

**Comment by gbinal** [comment]
Sorry, yes.  Game to merge?  

Thanks!

**Comment by gboone** [comment]
No worries.

**Pull request merged**
