### PR TITLE
Update home and what we deliver pages

### PR DESCRIPTION
**Pull request by apburnes**
Fixes issue(s) #2986

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/homepage-redesign/)

Changes proposed in this pull request:
- [x] Update homepage based on #2986 
- [x] Update `/what-we-deliver` based on #2986 
- [x] Need a new quote for the `/what-we-deliver` page (Reusing the FEC quote from the homepage for placeholder)
- [ ] ~Verify link locations for case studies~ (We'll tryout creating a new case studies page in a new issue: (**TODO: Create issue**))

### CODE REVIEW

**Comment by Dahianna** [comment]
Let's use this quote:

18F’s philosophy to build everything openly by default has been a key success factor in our ability to build credibility with the external stakeholders who have been critical of us previously.  More importantly, this way of building facilitates innovation in an eco-centric manner as opposed to just within the government or a few entities. - Christina Ho ( Former Deputy Assistant Secretary, Office of Accounting Policy & Financial Transparency, Department of the Treasury )

**Comment by apburnes** [comment]
Updated the quote.  Let me know what you all think. [`/what-we-deliver`](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/homepage-redesign/what-we-deliver/)

**Comment by Dahianna** [comment]
Looks good, I do have some questions regarding link's paths. Let's talk about them tomorrow during co-working.

**Comment by Dahianna** [comment]
**Homepage**
Include these agencies:
- Dept. of Agriculture
- U.S. Marine Corps (in #2978)
- Office of Management and Budget
- Center for Medicaid and Medicare Services (in #2978)
- U.S. Air Force (in #2978)
- National Geospatial Intelligence Agency (in #2978)

**What we deliver**
Remove `see all case studies>`
Include these case studies:
 - U.S. Forest Service: https://18f.gsa.gov/what-we-deliver/forest-service/
 - Alaska DHSS: https://18f.gsa.gov/what-we-deliver/alaska-dhss/
 - FBI: https://18f.gsa.gov/what-we-deliver/crime-data-explorer/
 - FEC: https://18f.gsa.gov/what-we-deliver/fec-gov/
 - DATA Act: https://18f.gsa.gov/what-we-deliver/data-act/
 - USKPA: https://18f.gsa.gov/what-we-deliver/state-uskpa/

**Comment by apburnes** [comment]
Should we change the section title from **Services** to **Case Studies** on the `/what-we-deliver` page?

image

**Comment by Dahianna** [comment]
That's actually one of the content changes I'm proposing (#2981). Let's leave it as is for now until I get them approved.

**Pull request merged**
