### PR TITLE
Blog tanf catchup

### PR DESCRIPTION
**Pull request by cmajel**
# Pull request summary
Adds "Catching up with the TDP project" blog post for publication on 8-30-2023. [Blog draft approvals here](https://github.com/18F/blog-drafts/issues/851#issuecomment-1697757279).

Question: My images are not loading in the[ build preview](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.sites.pages.cloud.gov/preview/18f/18f.gsa.gov/blog-tanf-catchup/2023/08/30/catching-up-with-the-tanf-data-portal-project/); there's a banner image and an inline image. Is that because of an error, or because of how assets build?

(Optional) Closes #(issue_number).

## Reminder - please do the following before assigning reviewer

- [ ] update readme
- [ ] For frontend changes, ensure design review

And make sure that automated checks are ok

- fix houndci feedback
- ensure tests pass
- federalist builds
- no new SNYK vulnerabilities are introdcued

### CODE REVIEW

**Comment by cmajel** [comment]
Things I can use help with here:
* I'm not sure why the workflow is failing here, or how to fix it
* I'm not sure if my img urls are formatted correctly. I copied what I saw on similar posts, but they don't appear in the preview.

**Comment by cmajel** [comment]
Testing out the new process here:

* @quarterback Can you give final content approval?
* @alexbielen @MelissaBraxton can you support on my open questions re post formatting?

**Comment by cmajel** [comment]
[Ron gave approval here](https://github.com/18F/blog-drafts/issues/851#issuecomment-1697876154)

**Comment by cmajel** [comment]
FYI I found and fixed a capitalization error in the `authors`, but the build still failed.

**Comment by alexbielen** [comment]
@cmajel I'm looking into the image issue now

**Comment by cmajel** [comment]
@alexbielen alt text updated

**Review by alexbielen — APPROVED** [review]
LGTM

**Comment by alexsobledotgov** [comment]
@alexbielen @cmajel I'm going to update the blog post `date` and filename to reflect our new planned pub date, Thursday 9/7.

**Comment by alexsobledotgov** [comment]
Done via fb867fc61f31ab681f659f91ce13f2390faed9aa.

**Comment by cmajel** [comment]
Thanks Alex(s)!

@alexbielen re process, would TLC merge and publish this tomorrow? Or should one of the authors plan on doing that?

**Comment by alexbielen** [comment]
@cmajel we're still very much figuring things out, but the mental model that I'm working with is that blog post authors, after getting approval from @quarterback, will hand the doc over to TLC Crew and TLC Crew will take it the rest of the way. 

So, yes I think that TLC Crew will merge it from here.

**Pull request merged**
