### PR TITLE
Add project pages prototype

### PR DESCRIPTION
**Pull request by gemfarmer**
Fixes issue(s) #1968 

[CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/project-pgs/)

[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/project-pgs/project/fec-gov)

Changes proposed in this pull request:
- adds new `/projects/` url and jekyll collection
- adds `project-tag-results.html` layout
- adds fec-gov.md file with the new project page template
- adds `match_posts`, a new way to filter for tags within non-post pages and collections with related documentation
- passes accessibility scan

/cc @coreycaitlin @ericronne

### CODE REVIEW

**Comment by gemfarmer** [comment]
@coreycaitlin and @ericronne can you take a look at the preview link when you get a chance?

**Comment by ericronne** [comment]
Not sure if i'm seeing the right page when i click the preview link above??

#1975 has the design for this.

**Comment by gemfarmer** [comment]
Test github integration comment

**Comment by gemfarmer** [comment]
Ignoring all houndCI commits because this is a vendor file.

**Comment by ericronne** [comment]
**Adjustments to bring it in line with the design in #1975 …**

## Grid reference ...

image


## Type styles (we can fine tune vertical spacing later) ...

image

**Comment by gemfarmer** [comment]
@ericronne does the small central column hold for all pages on the site, or just the project page?

**Comment by coreycaitlin** [comment]
@gemfarmer I think it's the same width as the main content column on How we work, Hire, and Join?

**Comment by ericronne** [comment]
@coreycaitlin yep, @gemfarmer pick up from those pp

**Comment by gemfarmer** [comment]
@coreycaitlin ah! you're right. I'll inherit from those pages.

**Comment by gemfarmer** [comment]
@ericronne layout margins updated! Feast your eyes on this layout!

**Comment by coreycaitlin** [comment]
@gemfarmer Nice! Can we do reverse-chron sort, and bring down the image sizes a bit? Methinks a slightly smaller size on those will make the page flow a little better.

**Comment by ericronne** [comment]
@gemfarmer can we use these type sizes? thx!

https://cloud.githubusercontent.com/assets/9259185/19986298/21cc904a-a1e4-11e6-968f-e96d28ca21d3.png

**Comment by gemfarmer** [comment]
@coreycaitlin certainly!

**Comment by gemfarmer** [comment]
this is good to go IMO. I reverse-croned the posts, shortened the image height, and updated the header sizes to Eric's specs. 

@ericronne @coreycaitlin  Lemme know what you think!

**Comment by ericronne** [comment]
@gemfarmer still doesn't seem to be using the styles i spec'd [above](https://github.com/18F/18f.gsa.gov/pull/2016#issuecomment-258281822)? :/

**Comment by gemfarmer** [comment]
@ericronne what specifically is off? I didn't touch the typography as I'm trying to stick as much as possible to USWDS. The images are not a specific column width because they are a specific column height

**Comment by coreycaitlin** [comment]
@gemfarmer Let's take a look at it later today in pairing?

**Comment by gemfarmer** [comment]
@ericronne We were discussing making style changes and the difficulty of determining what should be an 18F Site customization and what should be an architectural addition to the USWDS. I'm not clear on this just yet, but I think maybe having a conversation would clear things up. 

@coreycaitlin mentioned scheduling a convo with the USWDS peeps to hash this out. I think it would also behoove our team to internally discuss how much we want 18f.gsa.gov to be a reflection of USWDS vs an example custom site built on USWDS.

**Comment by ericronne** [comment]
@gemfarmer way better!!! This didn't involve any customizing other than the header image, right? I thought i applied existing type styles. 

Could we make this blue box one column narrower?
image

**Comment by ericronne** [comment]
Could you also increase the bottom margin of that panel from 30 to 60, to add space underneath it? Thanky!...

image

**Comment by gemfarmer** [comment]
@ericronne it is the same width as on the homepage. Are you thinking they should both be narrower?

**Comment by ericronne** [comment]
Only this one should be narrowed, since the overall graphic is much narrower. It's currently proportionally much wider than the home-page design.

**Comment by ericronne** [comment]
I mean **proportionately**, not proportionally ☝️

**Pull request merged**
