### PR TITLE
combine and minify styles

### PR DESCRIPTION
**Pull request by brendansudol**
__why__
we had 7 different stylesheets being loaded in the head, which creates additional
requests and negatively impact page load speeds.

__how__
we can use the built-in sass compiler to compile and minify all of these styles.

__before__
image

__after__
image

### CODE REVIEW

**Comment by theresaanna** [comment]
LGTM! 👍

**Comment by theresaanna** [comment]
One question, though -  are any documentation updates needed?

**Comment by brendansudol** [comment]
thanks @theresaanna. i just looked through documentation -- i don't believe any updates need to be made and none of the scripts should be are affected

**Comment by brendansudol** [comment]
thanks @theresaanna. i just looked through documentation -- i don't believe any updates need to be made and none of the scripts should be are affected

**Pull request merged**
