### PR TITLE
Avoid framing the benefits of openness as one of "surveillance"

### PR DESCRIPTION
**Pull request by konklone**
I totally get the idea here, and I do talk about the helpful benefits of our staff feeling vaguely watched as they do their work. As a government team, I think it'd be best to avoid references to CCTV cameras and surveillance as explicit analogies for this effect, though.

### CODE REVIEW

**Comment by gboone** [comment]
I agree with the impulse to avoid surveillance analogies, I think in this case it helps as an example of something specific in the "studies." @zacharycohn any thoughts on a different example we could use in place of surveillance here?

**Comment by zacharycohn** [comment]
Didn't we already sort of miss the boat on this?

**Comment by konklone** [comment]
I would still recommend changing it.

**Comment by awfrancisco** [comment]
I think it's still fine to make this update if it's important. @zacharycohn Do you have any other examples we could use?

**Comment by zacharycohn** [comment]
We can edit the first line to " Simply knowing someone could be seeing your
work has a demonstrable effect on behavior."

**Pull request merged**
