### PR TITLE
Cage match

### PR DESCRIPTION
**Pull request by melodykramer**

### CODE REVIEW

**Comment by gboone** [comment]
@melodykramer I'll work on converting this this morning, get it online by 1?

**Comment by melodykramer** [comment]
@gboone I converted it yesterday, and it should be on the branch cage-match. Just needs a look before pushing to staging. (Also: maybe a better picture?)

**Comment by gboone** [comment]
Oh, rad! I'll take a look.

**Comment by gboone** [comment]
Duh, I'm commenting on a pull request. :stuck_out_tongue_winking_eye:

**Comment by meiqimichelle** [comment]
yes yes yes .... can't wait for this!!!!

**Pull request merged**
