### PR TITLE
Update ruby pull request

### PR DESCRIPTION
**Pull request by eddietejeda**
merge from fork, to branch so ci can run

### CODE REVIEW

**Comment by Atul9** [comment]
@eddietejeda can you please rerun workflow on circle ci? please let me know how can I help

**Comment by eddietejeda** [comment]
Thanks for the pull request. This change appears to have surfaced other issues that I am now working on. Stay tuned.

**Comment by davemcorwin** [comment]
Its almost as if the working directory changes between identifying the spec files and actually opening them. When debugging locally, I also see inconsistent results in that sometimes rspec doesn't find any examples to run, so maybe there somehow is a race condition somewhere?

If I disable the Jekyll build when testing by commenting out [this line](https://github.com/18F/18f.gsa.gov/blob/master/spec/spec_helper.rb#L62), then I can consistently get the tests to pass as long as I work around references to ` Jekyll.sites[0].config` (since there are no `sites`)

**Comment by eddietejeda** [comment]
I know! It's very strange! I thought Ruby changed the way it did relative paths in this version of Ruby, but it looks like you're on the right track.

**Comment by apburnes** [comment]
## Todo

For the upgrade, review this issue:
https://github.com/18F/jekyll_pages_api_search/pull/41

which is related to this issue:
https://github.com/18F/jekyll_pages_api_search/issues/37

**Comment by apburnes** [comment]
Being unable to build the `jekyll_pages_api_search` index issue referenced in the previous comment is not effecting this PR.  The search index is being built as expected.  Additional testing for the search should be done to make search the functionality is working as expected.

**Pull request merged**
