### PR TITLE
New Blog Post: Senior executives are the allies tech teams need (pt 1)

### PR DESCRIPTION
**Pull request by colinmurphy01**
# Pull request summary
This adds a new blog post and 2 new author files for @allisonpresss and myself.

[Google Doc with draft and approvals](https://docs.google.com/document/d/1RYvI3N0rsLHhl79Lcjan76q6FTQIZlNdas1IajiIiTI/edit#heading=h.8lr0zxeowj1n)

### CODE REVIEW

**Comment by colinmurphy01** [comment]
Pausing review and publishing till we discuss with FCW about the WIP potential op-ed.

**Review by colinmurphy01 — COMMENTED** [review]
Look good to me, thanks @jstrothman

**Comment by jstrothman** [comment]
This post looks good to me. Per discussion w/FCW, 18F will wait to publish until day after the op-ed on their site goes live.

**Review by jstrothman — COMMENTED** [review]
approved 👍

**Pull request merged**
