### PR TITLE
Styleguide 2.0

### PR DESCRIPTION
**Pull request by gemfarmer**
Fixes issue(s) #2242 

[CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/styleguide-2.0)

[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/styleguide-2.0/styleguide/)

[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/styleguide-2.0/README.md)

Changes proposed in this pull request:
- shifts layout to fixed header and side nav
- breaks styleguide on to multiple pages
- addresses @jenniferthibault's [critique](https://github.com/18F/18f.gsa.gov/issues/2242#issuecomment-286813624)
- added new styleguide content:
  - introduction section
  - breadcrumb
  - right-aligned list
  - images and icons
  - blockquotes and pull quotes
  - blog images w/ and w/out captions
  - sticky subnavigation
  - technical notes on Jekyll
- re-ordered the nav
- removed unused plugins (namely author.rb)
- refactored plugins
- updated plugin README technical documentation

/cc @elainekamlley

### CODE REVIEW

**Comment by jenniferthibault** [comment]
@gemfarmer when I try the preview link, every time I click an item from the side menu I get one of these:

screen shot 2017-03-20 at 1 31 15 pm


Am I missing a step?

**Comment by gemfarmer** [comment]
@jenniferthibault You weren't missing anything! The links were broken on Federalist. They should be fixed now though!

**Comment by gemfarmer** [comment]
@jenniferthibault @gboone @awfrancisco Looking for feedback on the latest style guide improvements!

[:eyes: LOOK HERE 👀 ](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/styleguide-2.0/styleguide/)

**Comment by gemfarmer** [comment]
Merging and closing this issue, but we are going to keep #2242 open for additional comments and criticism!

**Pull request merged**
