### PR TITLE
Implement new contact page design

### PR DESCRIPTION
**Pull request by hbillings**
First pass at #2958. Note that this does not implement the mobile styles.

[CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/2958-contact-page)

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/2958-contact-page/contact/)

[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/BRANCH_NAME/README.md)

### CODE REVIEW

**Comment by eddietejeda** [comment]
Thanks @hbillings. When do you think the mobile work will be done?

**Comment by hbillings** [comment]
I'm back full time on a project, so my suggestion would be to merge this and address the mobile work in a separate ticket. (Also, I feel like the mobile design should probably be implemented as part of mobile design for the whole site, rather than for a single page, but that's just my gut.)

**Comment by eddietejeda** [comment]
https://github.com/18F/staffing-and-resources/issues/602

**Comment by maya** [comment]
Hello! Took this on from the design lab. Updated in f4f62a4 and should be good to go. Feel free to have @juliaklindpaintner give it a look, too.

**Comment by juliaklindpaintner** [comment]
Looks good to me, @maya! Thanks :)

**Comment by eddietejeda** [comment]
Thank @maya for doing this and thanks for approving @juliaklindpaintner.

Merging.

**Pull request merged**
