### PR TITLE
Publish 18F at 10 blog post

### PR DESCRIPTION
**Pull request by juliaklindpaintner**
Add blog post and image for 10th anniversary blog post

### CODE REVIEW

**Comment by juliaklindpaintner** [comment]
@quarterback Here's [the preview](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.sites.pages.cloud.gov/preview/18f/18f.gsa.gov/10-anniv-blog-post/2024/03/19/18f-at-ten/)! I currently have the title as "18F at Ten" per the doc title, but see that in the doc it's "18F turns ten" — what's your preference?

**Review by quarterback — APPROVED** [review]
Reviewed

**Comment by quarterback** [comment]
> @quarterback Here's [the preview](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.sites.pages.cloud.gov/preview/18f/18f.gsa.gov/10-anniv-blog-post/2024/03/19/18f-at-ten/)! I currently have the title as "18F at Ten" per the doc title, but see that in the doc it's "18F turns ten" — what's your preference?

18F at ten (per Jeff)

**Comment by quarterback** [comment]
I made the edits requested by comms and it's been reviewed by everyone.

**Pull request merged**
