### PR TITLE
Compress blog entry heroes

### PR DESCRIPTION
**Pull request by waldoj**
Fixes issue(s) # 2307.

[CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/image-optimization)

[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/image-optimization/)

Changes proposed in this pull request:
- turn a couple of JPEGs of screenshots into PNGs
- apply lossy compression to some JPEGs

### CODE REVIEW

**Comment by waldoj** [comment]
I figured I'd just go through the first few pages of blog entries and fix those, just to manage something bite-sized.

**Comment by gemfarmer** [comment]
@waldoj you're my hero! This really, really needed to be done. Thank you, thank you.

I'm going to change the base branch to `dev` so that this can go through our normal review process.

**Comment by waldoj** [comment]
When I do such things, should I be start by forking `dev` instead of `master`?

**Comment by gemfarmer** [comment]
@waldoj our general practice is that blog related updates get forked from `master`, while all other changes get forked from `dev`. We could probably make this more clear for folks as we run in to this issue a lot 😕

**Comment by waldoj** [comment]
Ahhh, great to know. It's possible I've learned this before, and now I'm re-learning it. May this be the final time that I learn it! :)

**Pull request merged**
