### PR TITLE
Publishes: Agile procurement resources for state and local government

### PR DESCRIPTION
**Pull request by gboone**
[CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/agile-procurement)

[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/agile-procurement/)

/cc @18F/blog @awfrancisco @mheadd @robincarnahan

### CODE REVIEW

**Comment by mheadd** [comment]
Looks like there is a typo in one of the links in the second to last paragrpah. Leading ```[``` around *state guidebook* is missing.

**Comment by gboone** [comment]
@mheadd that last commit should do it. LMK if it looks good.

**Comment by mheadd** [comment]
Ah, sorry to be a pain but wanted to ask - would it be possible to change the title of the post from "**Agile** procurement resources for state and local government" to "**Modular** procurement resources for state and local government"?

There's been a of of discussion in AcqStack lately about the term agile procurement and some concerns have been raised about its use - we're trying to move more consistently to modular procurement.

Thanks!

**Comment by gboone** [comment]
Yeah , we can do that. Head's up the URL will change when we change the title so links shared to the preview post will break.

**Comment by mheadd** [comment]
Understood. Thanks!

**Comment by gboone** [comment]
Alright, title change is in. I think that's it.

**Comment by mheadd** [comment]
Looks good to me. Thanks!

**Pull request merged**
