### PR TITLE
(WIP, scheduled for 12/3) Long Term Teams blog post

### PR DESCRIPTION
**Pull request by alexsoble**
[CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/BRANCH_NAME)

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/BRANCH_NAME/)

[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/BRANCH_NAME/README.md)

Changes proposed in this pull request:
- Add post

Checklist:
- [ ] All images being added have been optimized **_--> [learn more](18f.gsa.gov/styleguide/images/#using-and-optimizing-jpg-and-png) about how to optimize images <--_**

/cc @relevant-people

### CODE REVIEW

**Comment by alexsoble** [comment]
☝️ Hmmm ... I don't understand yet why the CircleCI tests are failing for this branch. Error: 

```
Configuration file: /home/circleci/project/_config.yml
jekyll 3.6.3 | Error:  no implicit conversion of nil into Array
```

This branch doesn't touch the `project/_config.yml` file or any other config, it just adds a blog post and images. Mystery! Will look at some other recent PRs to see if they offer any clues or if I'm missing a step here.

**Comment by lsgitter** [comment]
@Dahianna will take a look

**Comment by alexsoble** [comment]
@lsgitter, @Dahianna — @apburnes figured out the issue: the blog post didn't have any associated `tags`, which threw a test error. 

Thanks for figuring this out @apburnes! 🎉

**Comment by Dahianna** [comment]
Looks good! I'll go ahead and publish. Thanks Alex!

**Pull request merged**
