### PR TITLE
[WIP] Accesslint

### PR DESCRIPTION
**Pull request by gemfarmer**
Fixes issue(s) #1993 #https://github.com/accesslint/accesslint-ci/issues/28

[CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/accesslint)

[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/accesslint/)

Changes proposed in this pull request:
- [x] adds configuration for accesslint to circle.yml. This will compare any new PR against master and make comments if there are _serious_ or _critical_ errors in the site.
- [ ] add documentation for getting this set up on a Jekyll site
- [ ] remove commands and associated documentation for pa11y-ci. Consider not fully removing documentation (it worked, was just too slow for this build)

/cc @maya @ckundo

### CODE REVIEW

**Comment by ckundo** [comment]
Hi @gemfarmer, I'm investigating the timeouts with accesslint-ci. Tracking notes and progress here https://github.com/accesslint/accesslint-ci/issues/42.

**Comment by gemfarmer** [comment]
@ckundo Thanks! I'm running into issues with ```already initialized constant Readline::HISTORY```, which I assume might have something to do with the fact that we are building the site twice?? I'm going to try a build where the `bundle exec jekyll build` command runs after the site has been served and scanned [here](https://circleci.com/gh/18F/18f.gsa.gov/832)

**Comment by gemfarmer** [comment]
@ckundo what configuration did you have when you were getting the legitimate errors?

**Comment by ckundo** [comment]
@gemfarmer take a look at the artifacts tab for the timed out build, the AccessLint log should have contents.

**Comment by gemfarmer** [comment]
@ckundo I see the artifacts, but no content logs, per se. Do I need to disable artifacts to receive comments?

**Comment by ckundo** [comment]
Here's the artifact I had in mind: https://832-17324120-gh.circle-artifacts.com/0/home/ubuntu/18f.gsa.gov/tmp/accesslint.log

The comments on the PR will only be posted after the `accesslint-ci` finishes spidering content. What's happening is that the build step is timing out before accesslint can finish, and so no comments get posted to the PR.

I'm looking more closely at the builds, I think it's specific to something in your project configuration, content, or routes.

**Comment by ckundo** [comment]
@gemfarmer the `Readline` warning looks related to https://github.com/ConnorAtherton/rb-readline/issues/129. I suspect jekyll server uses a release of rb-readline as a dependency that triggers that warning.

**Comment by ckundo** [comment]
@gemfarmer the reason the scanning is timing out is that accesslint is scanning the entire history of the blog, which is a few hundred individual pages. I'm confident it will complete given enough time, and can configure a PR to demonstrate that.

**Comment by ckundo** [comment]
@gemfarmer I'm setting up a way to filter specific directories from a scan, in your case filtering the blog pages. I'll share the results and code in a few.

**Comment by gemfarmer** [comment]
@ckundo thanks again for your timely responses. This all makes a bit more sense to me. Will the scanner always crawl all of the pages, or can we make it only scan pages relavent to the PR? Is this just happening this first time to create a baseline for comparison?

**Comment by ckundo** [comment]
@gemfarmer the audit will always run on all pages that are served by the jekyll serve command, but will only comment with new issues. I noticed there are `serve` and `serve-blog` scripts in the repo. I’m playing with running accesslint-ci using the `serve` script as a model, since I think it excludes the blog.

**Comment by gemfarmer** [comment]
The `serve-blog` script may be a bit of a misnomer. It serves the site + the latest 3 blog posts. We want to lint the blog posts, but really, the latest ones are most likely to include editing. Perhaps I could make another script that only includes posts that are in the diff ??

**Comment by ckundo** [comment]
@gemfarmer if you run CI for each new blog post, then the `serve-blog` script seems like it would give us the coverage we need! I'll give it a shot and post an update later in.

**Comment by gemfarmer** [comment]
@ckundo Thanks! I'm also going to try to get to this early next week when I have more bandwidth!

**Comment by ckundo** [comment]
@gemfarmer we're quite close. I may have something this evening to submit back.

**Comment by gemfarmer** [comment]
Woah! Quick work @ckundo! I'll keep an eye out for it!

**Comment by ckundo** [comment]
Here's are the changes to only look at recent posts when scanning with accesslint-ci: https://github.com/18F/18f.gsa.gov/pull/2132

**Comment by coreycaitlin** [comment]
Closing in favor of #2134

**Pull request closed without merging**
