### PR TITLE
Measuring culture on our engineering team post

### PR DESCRIPTION
**Pull request by Dahianna**
**DO NOT MERGE UNTIL 10/31**

[CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/survey-post)

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/survey-post/)

[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/survey-post/README.md)

Changes proposed in this pull request:
- Add post to blog

### CODE REVIEW

**Comment by Dahianna** [comment]
@amymok and @alexsoble this is ready for you to add the image and tables.

**Comment by amymok** [comment]
@Dahianna Thank you so much! I probably may not have time to look until Monday, I will work with @alexsoble on the charts!

**Comment by alexsoble** [comment]
@Dahianna Doing a little pre-work on this before our meeting — adding @pburkholder as an author and adding in images.

**Comment by alexsoble** [comment]
Spoke with @Dahianna over Slack — we are going to move the publication date to this Thursday 10/31 in order to do a thorough accessibility check and find a nice header image if possible.

**Comment by alexsoble** [comment]
@apburnes — @amymok did a final check last night, this is now ready to merge! Thanks for your help! ❤️

**Pull request merged**
