### PR TITLE
New agency list

### PR DESCRIPTION
**Pull request by gemfarmer**
Fixes issue(s) #2327 

[CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/agency-list)

[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/agency-list/what-we-deliver/#agencies-weve-worked-with)

Changes proposed in this pull request:
- added agencies from [this spreadsheet list](https://docs.google.com/spreadsheets/d/1FZJvf2e8GdRlLp3zI-xEN2Y9ai0w2S6URStW2MrBCLE/edit#gid=0) **_This list needs to be finalized before merging_**
- created `agencies.yml` to house them. Can add more information, such as links, if it becomes relavent

/cc @gboone @awfrancisco @coreycaitlin

### CODE REVIEW

**Comment by awfrancisco** [comment]
How is this list ordered? Also, I'd vote to remove all abbreviations to make the list look more consistent.

**Comment by gemfarmer** [comment]
@awfrancisco this is [the list](https://github.com/18F/18f.gsa.gov/pull/2348/files#diff-280d9ac5d8d1ebd75a444d42819d7293) used and the order is left – right column, top – bottom.

I can remove the abbreviations, though I'll say that it was still inconsistently formatted before I added those.

**Comment by awfrancisco** [comment]
Sounds good. Thanks for putting this together. 

Let's put this on the agenda for a standup/coworking to discuss which to include and how to organize them.

**Comment by gemfarmer** [comment]
This now includes the more refined list _and_ has logos

**Comment by gemfarmer** [comment]
One potential problem that might need to be addressed before merging: several of the svg logos are pretty slow to load. This is unusual for SVGs, but I noticed that several of them are referencing external PDFs to generate the graphics. If other people are experiencing loading issues it might be nice to comb through those and find alternative SVGs or PNGs that don't have this problem

**Comment by gemfarmer** [comment]
I replaced some of the slow loading SVGs with optimized PNGs. Now playing around with the idea of changing the icon size.

## Large:
screen shot 2017-03-13 at 2 00 18 pm
## Medium:
screen shot 2017-03-13 at 2 00 03 pm
## Small:
screen shot 2017-03-13 at 1 59 57 pm

**Comment by awfrancisco** [comment]
And which list of agencies is this pulling from? Medium or small?

**Comment by gemfarmer** [comment]
Pulling from medium list of agencies

**Pull request merged**
