### PR TITLE
Publishes "How reusable is open source software" blog post

### PR DESCRIPTION
**Pull request by elainekamlley**
[CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/reuse-open)

[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/reuse-open/)

[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/reuse-open/README.md)

Changes proposed in this pull request:
- Adding content for open source blog post

/cc @lauraGgit @gboone

### CODE REVIEW

**Comment by lauraGgit** [comment]
So exciting!

**Comment by elainekamlley** [comment]
@lauraGgit have any last minute edits?

**Comment by lauraGgit** [comment]
Any chance we could change this:

**Comment by lauraGgit** [comment]
"If your IT team tries to import an existing codebase wholesale, whether or not the code is open or closed, the product will likely lack features that your users absolutely need, leaving your end users unsatisfied."

This sentence feels a little awkward, but its not a show stopper!

**Comment by elainekamlley** [comment]
How's this - "If your IT team tries to import an existing codebase, the product will likely lack features that your users absolutely need, leaving your end users unsatisfied."

**Comment by lauraGgit** [comment]
Could we do "If your IT team tries to import an existing codebase wholesale, the product will likely lack features that your users absolutely need, leaving your end users unsatisfied."

**Comment by elainekamlley** [comment]
@lauraGgit pushed up that edit. If everything else looks good, we'll publish this tomorrow afternoon.

**Comment by lauraGgit** [comment]
@elainekamlley looks good to me! 🚀

**Pull request merged**
