### PR TITLE
Ik guide icons

### PR DESCRIPTION
**Pull request by igorkorenfeld**
The icons on the current guides page don't have enough contrast against the background.

Additionally, the distance between the icon and the link below it nearly the same as the distance between the link above it. It is more clear to group the items that are a unit together with less space, and keep more space between individual items. 

Proposed: 👓 &nbsp;[Preview](https://federalist-d703a102-c627-4805-8934-78f5bf4c97da.app.cloud.gov/preview/igorkorenfeld/18f.gsa.gov/ik-guide-icons/guides/)

@cmajel and @Dahianna wanted to get your input first so this is a draft pull request.

### CODE REVIEW

**Comment by Dahianna** [comment]
@igorkorenfeld looks good to the site team! @cmajel let me know when you're done reviewing and I'll merge

**Comment by cmajel** [comment]
@Dahianna @igorkorenfeld looks good to me 👍

**Comment by Dahianna** [comment]
Awesome! I'll go ahead and merge

**Comment by igorkorenfeld** [comment]
I think it should be all set!

**Pull request merged**
