### PR TITLE
adding Will's pic

### PR DESCRIPTION
**Pull request by wslack**

### CODE REVIEW

**Comment by wslack** [comment]
I don't know where the data for my name comes from, so this probably isn't ready yet.

**Comment by gboone** [comment]
All you need to do is make sure the name of the file matches your 18F/data-private team file. Happy to help further if that is confusing or unhelpful.

**Comment by wslack** [comment]
I accidentally did that correctly; we're all set.

**Comment by gboone** [comment]
Great! I'll check it out and merge if it's all :ok_hand:

**Comment by gboone** [comment]
Looks good, thanks @wslack!

**Pull request merged**
