### PR TITLE
Add 404.html page to squelch AccessLint errors in development

### PR DESCRIPTION
**Pull request by ckundo**
- AccessLint was commenting on errors in the development server's 404
  page, which is a built in page in Webrick that was missing semantics
  required for accessibility.
- jekyll looks for a 404.html in the project directory to override
  the development server 404 page.
- jekyll implementation is here: https://github.com/jekyll/jekyll/pull/1899/commits/99b36c7c308e0bbd2fe9b3b65850ac43af39530d
- Test this by running this command locally. There should be no
  accesslint errors.

        ./serve-accesslint && bundle exec accesslint-ci scan --skip-ci http://localhost:4000/page-that-does-not-exist

- The production build should continue to use pages/404.md.

/cc @gemfarmer

### CODE REVIEW

**Comment by gemfarmer** [comment]
@ckundo Thanks! I'm going to change the base branch to `dev`

**Comment by ckundo** [comment]
@gemfarmer I'm not 100% sure how your production build environment works, so I'll leave it to you to verify the last point:

> The production build should continue to use pages/404.md.

**Comment by gemfarmer** [comment]
@ckundo this won't work in the production build environment, but if can add an `exclude: 404.html` to the `_config.yml` and `include: 404.html` to `_config-accesslint.yml`, we might be able to enable the 404 you might _only_ for the accesslint local environment.

**Comment by gemfarmer** [comment]
@coreycaitlin I'll get this in next week after we merge the remaining changes needed for the next push to production

**Comment by gemfarmer** [comment]
Closing in favor of #2346

**Pull request closed without merging**
