### PR TITLE
Adding Brad's photo

### PR DESCRIPTION
**Pull request by bradnunnally**
Here is Brad Nunnally’s photo.

### CODE REVIEW

**Comment by gboone** [comment]
Thanks @bradnunnally, could you resize it to 250 x 250 px?

**Comment by elainekamlley** [comment]
Hey @bradnunnally, if you don't have time to crop your photo you can upload it to google drive and I can do it for you. https://drive.google.com/drive/u/1/folders/0B8kn3cuJUwEkLUMwWXE2VVczbUU

**Comment by bradnunnally** [comment]
@gboone & @elainekamlley So sorry I missed these comments!!!! I've just committed a new photo to this pull request and the photo is at 250 x 250 now. 

Sorry it's taken me so long.

**Comment by elainekamlley** [comment]
:+1: Thanks @bradnunnally!

**Comment by gboone** [comment]
No worries! Glad we got you squared away.

**Pull request merged**
