### PR TITLE
Add boon sheridan and publish new post

### PR DESCRIPTION
**Pull request by juliaklindpaintner**
# Pull request summary
Adds Boon Sheridan's author file and a new blog post

### CODE REVIEW

**Comment by juliaklindpaintner** [comment]
Blog post [preview is here](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.sites.pages.cloud.gov/preview/18f/18f.gsa.gov/Add-Boon-Sheridan-and-publish-new-post/2024/01/31/gathering-feedback-with-customer-panels/)

**Review by cantsin — APPROVED** [review]
LGTM!

**Comment by cantsin** [comment]
We have a failing CI check -- did we want to fix that first before merging?

**Comment by juliaklindpaintner** [comment]
Thanks @cantsin — I saw that but don't know how to fix... Can you help?

**Comment by cantsin** [comment]
We are good to go now. #3801 fixed the issue. We can merge when-ever.

**Pull request merged**
