### PR TITLE
[WIP] Adding VP and mission statement language

### PR DESCRIPTION
**Pull request by awfrancisco**
**WORK IN PROGRESS. DO NOT MERGE.**

Fixes issue(s) #2494

[CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/add-vp-mission)

[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/add-vp-mission/)

[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/add-vp-mission/README.md)

Changes proposed in this pull request:
- New homepage language. 
- New featured homepage projects
- New intro on what we deliver page
- Move principles from about page to how we work page. New introduction to guides on how we work.
- New language on contact us page

### CODE REVIEW

**Comment by smils** [comment]
On HWW page (additions in all caps):

18F partners with federal agencies to help you deliver EXCEPTIONAL digital experiences that address your strategic initiatives. Each engagement is structured as a close partnership between an 18F team and your agency. Our work together is guided by ~~focusing on~~ user-centered development, testing to validate hypotheses, SHIPPING OFTEN, and deploying products in the open. Learn a little bit ~~more~~ below or find more information in the 18F Partnership Principles and the U.S. Digital Services Playbook.

[Section of bullets below needs a sub-head]
[Question: are the list of things in "Our work together" too jargony for the public?]

**Comment by smils** [comment]
WWD page:

Proven experience helping agencies across the government ~~better serve their users~~deliver better value to the American public

**Comment by smils** [comment]
Contact page:

Since the button on the home page is "Get in touch," and it comes here, let's change this button to "Email us." Otherwise it suggests the button loops you back to this page.

**Comment by smils** [comment]
Home page:

I'm concerned that the three bullets w/the types of work we do are a little random w/o a direct header. Did you play with subheads? If not, can we?

**Comment by smils** [comment]
Overall, @awfrancisco @elainekamlley, updates look fantastic! Comments above are relatively niggling.

**Comment by awfrancisco** [comment]
@elainekamlley Can you take a look at the "Home page" comment from Sarah above? Could we add a header above the 3 buckets on the homepage?

**Comment by elainekamlley** [comment]
Looks good!

**Pull request merged**
