### PR TITLE
New homepage

### PR DESCRIPTION
**Pull request by gemfarmer**
[CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/homepage)

[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/homepage/)

Changes in this PR:
- updates styleguide
- updates homepage to look like the following (with a few additional updates):

screen shot 2017-01-11 at 1 41 32 pm

/cc @austinhernandez @coreycaitlin @elainekamlley

### CODE REVIEW

**Comment by gemfarmer** [comment]
Dear @austinhernandez, 

Here is a list of remaining items/things to discuss

- Top banner
  - [ ] Width of blue space. Should it be a set or fluid width (I'll explain)
  - [ ] Cropping on image. Do we like it how it is?
- "We support your mission" section
  - [ ] Font sizes
  - [ ] spacing 
  - [ ] alignment
- Featured projects section
  - [ ] What size images should we use for the cards
  - [ ] box shadows
  - [ ] anything else?
- Blog posts
  - [ ] Any changes that I haven't noticed

**Comment by gemfarmer** [comment]
@austinhernandez grid changes have been made. Ready for review!

**Comment by coreycaitlin** [comment]
Tofix before merging:

- [ ] main blog layout has a weird breakpoint, and images are dropping below posts

**Comment by gemfarmer** [comment]
@coreycaitlin I fixed the blog layout weirdness in 339e330!

**Comment by gemfarmer** [comment]
@austinhernandez @coreycaitlin pushed some new updates addressing hover state improvements and "We support your mission" layout improvements. Lemme know what you think!

**Comment by coreycaitlin** [comment]
I think this looks pretty stable and we should get it merged into dev for final review!

**Comment by gemfarmer** [comment]
WOO!

**Pull request merged**
