### PR TITLE
Unpublish guys bot post

### PR DESCRIPTION
**Pull request by awfrancisco**
[CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/guys)

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/guys/)

[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/guys/README.md)

Changes proposed in this pull request:
- Unpublishes guys bot post
- Redirects guys bot post to blog homepage

### CODE REVIEW

**Comment by ferlatte** [comment]
I am also curious why this content was removed; this has become a fairly common practice in many organizations and this article was a good resource.

**Comment by gbinal** [comment]
I'm confused and worried about how this came to pass.

**Comment by theory** [comment]
This was a great resource; is there a reason it was removed?

**Comment by lukefretwell** [comment]
Would love to hear the rationale for doing this, especially since it appears, based on @DsaleGov's user history, he joined GitHub just to accept the PR merge to delete this post.

**Comment by annepetersen** [comment]
Republished, for reference: https://github.com/18F/18f.gsa.gov/commits/7a6cf04f63d83f9b41820e36e15a7a3064311d82/_posts/2016-01-12-hacking-inclusion-by-customizing-a-slack-bot.md

**Pull request merged**
