### PR TITLE
Fix styles link

### LINKED ISSUE #3848: Migrate styles
One of the things I'm noticing is that the link to the styles CSS is the only broken link in the site right now:

```
Check HTML Links
  📖 Found 1051 files containing
    🔗 46998 internal links
  👀 Checking...
  ❌ Found 1 missing reference targets (used by 957 links) while checking 1051 files:
    1. missing reference target _site/assets/css/styles.css
      from _site/2014/03/12/coming-soon/index.html:60:8 via href="/assets/css/styles.css"
      from _site/2014/03/19/hello-world-we-are-18f/index.html:60:8 via href="/assets/css/styles.css"
      from _site/2014/03/21/29-minutes/index.html:60:8 via href="/assets/css/styles.css"
      ... 954 more references to this target
```

```[tasklist]
### Acceptance criteria
- [x] Styles are correct, and showing the equivalent of what we see on 18f.gsa.gov (prod)
```

### PR DESCRIPTION
**Pull request by jasnakai**
# Pull request summary for #3956

This PR migrates the styles from the live 18f website to the replatformed site. The handling of scss files and their organization were updated. Updated styles are now loading.

Closes #3848.

## Reminder - please do the following before assigning reviewer

- [x] Update readme

And make sure that automated checks are ok

- fix houndci feedback
- ensure tests pass
- federalist builds
- no new SNYK vulnerabilities are introduced

### CODE REVIEW

**Comment by beechnut** [comment]
Your work here made it apparent for the first time that we've been missing the correct footer content.

Screenshot 2024-07-02 at 10 32 34 AM (2)
```
Left: localhost                                       Right: production
```

So, I've added back the correct footer, but now the category headers aren't looking right

Screenshot 2024-07-02 at 10 50 04 AM (2)

```
Left: localhost                                       Right: production
```

This is just on the border of "scope creep", so I'll leave it to you: do you want to do that fix in this ticket (I can push the footer), or should we open another ticket for that?

**Comment by jasnakai** [comment]
I will give a quick check and if it seems like a large lift, I will break it out into its own ticket. Thanks!

**Comment by beechnut** [comment]
My initial investigation shows that all the classes are the same, but for some reason the `font-weight: 500` in prod isn't showing up locally, and that it's computing as `font-weight: 100`.

**Comment by jasnakai** [comment]
@beechnut I believe I fixed the issues you highlighted as well as a couple other styling issues for the footer.

**Comment by beechnut** [comment]
I've been trying to review this latest commit, but I'm having trouble even getting styles to render. I think it has something to do with the transient `_data/assetPaths.json` stuff.

**Comment by beechnut** [comment]
1. (blocking) Okay, so — for some reason, I get styles on every page except for `/our-work/`. Any chance you get the same thing?

2. (non-blocking) Blockquote line heights are different, at least in blog posts (feel free to ignore the content differences). It's not big enough of a difference that I'll hold up approval for this, we can always put it in a post-migration task, but it was noticeable.

Screenshot 2024-07-03 at 2 35 39 PM
Screenshot 2024-07-03 at 2 35 34 PM

**Comment by beechnut** [comment]
I fixed the blockquote thing — the Jekyll site was using HTML tags for blockquotes, and changing them to regular markdown fixed the spacing and the rendering.

So, just the our-work styles are what's blocking approval. Thanks :)

**Comment by jasnakai** [comment]
Thank you!

**Comment by beechnut** [comment]
Turns out the our-work page had no layout specified! Jekyll may have had an implicit default layout, but 11ty seems more explicit.

Changing layouts is separate from this story, so we're good here! Approved!

**Review by beechnut — APPROVED** [review]

**Pull request merged**
