### PR TITLE
Edits to discovery research blog entry

### PR DESCRIPTION
**Pull request by waldoj**
Fixes issue(s) #2459.

Changes proposed in this pull request:
-clarify confusing text
-copyediting changes
-improve linked text

/cc @rrefoy

### CODE REVIEW

**Comment by waldoj** [comment]
I don't know how to ensure that a Circle CI test is run, given that the template for a pull request specifies a branch name, and I didn't make these changes on a branch, but instead on a fork.

**Comment by awfrancisco** [comment]
@elainekamlley can you help with the CircleCI issue?

**Comment by elainekamlley** [comment]
@waldoj could you submit this through a branch instead of a fork? We like to have circleCI run before merging. Thanks!

**Comment by waldoj** [comment]
Closed in favor of #2462.

**Pull request closed without merging**
