### PR TITLE
renamed news to blog

### LINKED ISSUE #356: redirect /blog to /news
plz

### PR DESCRIPTION
**Pull request by elainekamlley**
Changed the following areas from `/news` to `/blog`:

- _config.yml
- global nav button
- took out `back to all posts` button in blog post layout
- renamed news folder to blog folder

closes #356

### CODE REVIEW

**Comment by konklone** [comment]
Huge :+1: for this change. How will redirects be handled?

**Comment by gboone** [comment]
We were just talking about that. I'm thinking an nginx rewrite rule. Something like:
```
rewrite ^(/news/.*)/blog/(.*)\..*$ permanent;
```

**Comment by konklone** [comment]
That will totally work (haven't verified the syntax), but the less in nginx, the better. The more we put in there, the harder it is to leave nginx. 

Can we do this with Jekyll directly? Thankfully, we never included `/news` or `/blog` in our actual post URLs, e.g. `https://18f.gsa.gov/2015/02/09/the-first-gov-domains-hardcoded-into-your-browser-as-all-https/`, and even the tags page doesn't have `/news` in it.

So we only have to change `/news/`, from what I can tell. That's a `<meta refresh>` tag away.

**Comment by gboone** [comment]
We could do that. I'm told doing redirects server-side is preferred when possible, but as long as search engines get the 301 redirect I don't know that it totally matters. The only pages that are affected are `/news` and `/news/page/*`

**Comment by konklone** [comment]
You're right, server-side is preferred, though a small number of `<meta refresh>~ tags with a refresh of `0` will be treated as a 301 redirect by Google and Yahoo, and shouldn't cause us to get flagged as spam (having reams of meta refreshes can be a bad signal). In my opinion, it's a better balance in terms of the flexibility of the site.

**Pull request merged**
