### PR TITLE
Join us post

### PR DESCRIPTION
**Pull request by gboone**

### CODE REVIEW

**Comment by konklone** [comment]
Doing a couple quick technical edits, then will merge.

**Comment by konklone** [comment]
Is there an OG image?

**Comment by konklone** [comment]
I changed the images to move them to the `assets/blog` dir.

I'm done - after the OG image link is added, :+1: any time.

**Comment by gboone** [comment]
Good catch on those Google encoded URLs, @konklone, I pushed up the og-image with 5898875

**Pull request merged**
