### PR TITLE
add credit for Mollie R's org

### PR DESCRIPTION
**Pull request by wslack**
Super small PR to add USDS to the list of agencies, since the USWDS was originally a proposal from @mollieru of USDS (who partnered with 18F to execute).

### CODE REVIEW

**Comment by lsgitter** [comment]
@Dahianna @margaretmildrew  Is this something we can approve in github?

**Comment by Dahianna** [comment]
If the author agrees, we can approve and merge

**Comment by mollieru** [comment]
Just saw this -- thanks @wslack! 

Just for the purposes of history, there were a number of other folks from USDS involved in the initial launch including Angel Kittiyachavalit and Victor Garcia.

**Comment by wslack** [comment]
<3 @mollieru 

Also @amyashida did anyone ask you to check this?

**Pull request merged**
