### PR TITLE
About page design / consolidate templates

### PR DESCRIPTION
**Pull request by gemfarmer**
Fixes issue(s) #2245 

[CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/about-squashing)

[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/about-squashing/)

Changes proposed in this pull request:
- [x] Updates about page to new design
- [x] Consolidates the `default-image` and `default-intro` templates to **`default-intro`** layout
- [x] Updates the page intro/lead section to have two lines. 
  1. Title
  2. Lead content
- [x] updates accessibility text on icons

/cc @austinhernandez @coreycaitlin

### CODE REVIEW

**Comment by gemfarmer** [comment]
@coreycaitlin I think this is in a good place for you to look at!

**Comment by coreycaitlin** [comment]
This is beautiful! I made a tweak to remove the duplicate lead text on non-image pages, and added dividers on the /join page.

**Comment by gemfarmer** [comment]
@coreycaitlin great, thanks. Did you want to edit content before merging, or can I merge and address any remaining content later?

**Comment by gemfarmer** [comment]
@coreycaitlin Based on [this comment], I'll take that as a _ready to merge_

**Pull request merged**
