### PR TITLE
Modular contracting and working in the open post

### PR DESCRIPTION
**Pull request by Dahianna**
[CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/modular-contracting-open-post)

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/modular-contracting-open-post/)

[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/modular-contracting-open-post/README.md)

Changes proposed in this pull request:
- Add image to assets
- Publish blog post

Checklist:
- [x] All images being added have been optimized **_--> [learn more](18f.gsa.gov/styleguide/images/#using-and-optimizing-jpg-and-png) about how to optimize images <--_**

/cc @awfrancisco

### CODE REVIEW

**Comment by awfrancisco** [comment]
This is for thursday right?

**Comment by Dahianna** [comment]
@awfrancisco Yes, for Thursday

**Comment by Dahianna** [comment]
I just noticed the image is not coming up. Not sure why but looking for a solution

**Comment by Dahianna** [comment]
@awfrancisco can you take a look? The code seems to be right and the image is in the folder

**Comment by awfrancisco** [comment]
The `i` in `image` in the front matter needed to be lower cased. I also updated the date. When the tests pass, I can merge.

**Comment by Dahianna** [comment]
Test passed. Looks good! Let me send the link to Mark and Ed for a final review

**Pull request merged**
