### PR TITLE
Create 2015-02-19-the-many-talents-18f-is-looking-to-hire

### PR DESCRIPTION
**Pull request by melodykramer**
This needs some work. I have a meeting right now and will adapt it when I return.

### CODE REVIEW

**Comment by gboone** [comment]
ping: @cscairns @NoahKunin @russu @kaitlin 

Chris, there was a footer you wanted on the hiring microsite: http://18f.github.io/hiring/, I thought you said the text was in this post somewhere but I'm not seeing it. Can you point me to it?

**Comment by gboone** [comment]
Never mind, I found it, but we have a follow up question. The text of the post says there are 10 categories but there are 11 listed in the post, and 13 listed on 18f.github.io/hiring, should we add bullets for all 13 or keep the 11 in the post?

**Comment by kaitlin** [comment]
Oh these are adapted from the agile BPA descriptions. What happened to the doc with the map of our locations and the other set of descriptions?

**Comment by gboone** [comment]
@kaitlin I've been wondering the same thing. This is a blog post based on a different doc: https://docs.google.com/a/gsa.gov/document/d/1XssWmtXmiCGes8ZL5couCW8XFgagmR_7jCfW309cbGI/edit which included a link to the BPA descriptions. I'm tempted to hold until I have better clarity on what the difference and relation between these documents and the doc you're mentioning.

**Comment by kaitlin** [comment]
Also, in general I don't need to be listed as an author on a blog post I didn't write.

**Comment by russu** [comment]
I'll +1 Kaitlin on that. If for some odd reason having my name associated
seems to help, that's cool, however, there was no writing by me, so it
feels strange to snipe some credit there.

On Thu, Feb 19, 2015 at 11:41 AM, Kaitlin Devine <notifications@github.com>
wrote:

> Also, in general I don't need to be listed as an author on a blog post I
> didn't write.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/18f.gsa.gov/pull/541#issuecomment-75098988>.
>



-- 

*Russ Unger*
Director, Experience Design Center of Excellence
18F

**Pull request merged**
