### PR TITLE
Elaine changes to style guide

### PR DESCRIPTION
**Pull request by elainekamlley**
Fixes some issue in #2410 

Changes proposed in this pull request:
- Sticky subnavigation:
  - [x] Change “heading two” to “heading 2”
  - [x] Show examples of where we have this within the site
- Images: 
  - [x] Removed some images and added documentation
- Blog: 
  - [x] renamed `blog` to `blog components`
- Layout: 
  - [x] People seemed to expect templates or layouts for the site, not a description of classes
  - [x] Move right aligned list to example of layout, not in components
  - [x] Rename right-aligned list to sidebar
  - [x] Examples for how to populate data within a layout (think sidebar)

/cc @gemfarmer

### CODE REVIEW

**Comment by gemfarmer** [comment]
[PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/sg-5-elaine/styleguide/) (for my own purposes)

**Comment by gemfarmer** [comment]
Thoughts: 
- It looks like the right-aligned list was moved to layouts/sidebar, but also still exists at [components/right-aligned-list](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/sg-5-elaine/styleguide/components/#right-aligned-lists)

**Comment by elainekamlley** [comment]
@gemfarmer thanks for the catch! Updated the components markdown file.

**Comment by gboone** [comment]
Awesome work, @elainekamlley! Thanks for the review, @gemfarmer.

**Comment by gemfarmer** [comment]
@elainekamlley awesome! Thanks for finishing that up @elainekamlley!

**Pull request merged**
