### PR TITLE
Layering Innovation

### PR DESCRIPTION
**Pull request by awfrancisco**

### CODE REVIEW

**Comment by NoahKunin** [comment]
Already past noon on a Friday. Hold to Monday for a stronger hit? @dlapiduz  @awfrancisco ?

**Comment by NoahKunin** [comment]
Based on a presumption, not any current real data on when people read things online. It's been years since I looked at that stuff.

**Comment by awfrancisco** [comment]
@NoahKunin That's my presumption too. Fine with me to hold. Maybe have the team do a final review today so we are cleared just to merge it Monday morning.

**Comment by NoahKunin** [comment]
@andrewmaier: looks like myself, Congressional, Comms, and Outreach have all :+1: so we're good on executive support. 

@dlapiduz sound good to share the heck out of this on Monday?

**Comment by dlapiduz** [comment]
I'd say lets put it out ASAP but if you want to do it monday then lets hold

**Pull request merged**
