### PR TITLE
Improving font performance.

### PR DESCRIPTION
**Pull request by msecret**
This method asynchronously loads fonts as soon as possible, while not
blocking render, then stores the result in localStorage for future
visits.

This has been documented here:
http://www.filamentgroup.com/lab/font-loading.html

TODO, there could be improvements made to this later down the line:
- Separate each type of font file (ttf, woff) into a separate file
with font data base64 encoded. Program if statement for different types
- Use font loading events to apply font class after font loaded.

### CODE REVIEW

**Comment by konklone** [comment]
> * Use font loading events to apply font class after font loaded.

I don't see this evident in the code - can you point out where font events are used? (I do see an XHR event.) I also don't see any classes used here.

**Comment by msecret** [comment]
Sorry for not being clear, the bottom two points are what could be done in the future for improved performance.

I didn't do them this time to keep the code compatible with your changes and also because I haven't tested the other method yet.

The solution I have now is good enough performance. I'm going to try and develop a slightly better method in the future.

**Comment by konklone** [comment]
Ahhhh, I skimmed your original issue description too fast, I'm sorry. -_-

Looks good to me!

**Comment by konklone** [comment]
Am I right in assuming this method of font optimization works whether or not the fonts have been inlined, or loaded dynamically from Google Fonts? Does having inlined them make any difference to the approach?

**Pull request merged**
