### PR TITLE
Capitalization standardization through end of 2014

### PR DESCRIPTION
**Pull request by emileighoutlaw**
Headlines, sub-heads, and some other tricky words fixed (lists, government, federal, agile, and so on)!

### CODE REVIEW

**Comment by konklone** [comment]
my god

**Comment by kategarklavs** [comment]
YESSSS!

**Comment by gboone** [comment]
Wow. Thanks @emileighoutlaw!

**Comment by emileighoutlaw** [comment]
Thanks!!

**Pull request merged**
