### PR TITLE
Allow VDP to used for testing pre-release

### PR DESCRIPTION
**Pull request by pburkholder**
# Pull request summary

Allows VDP and bug bounty to apply pre-release when authorized.

Tag @LindsayYoung @JJediny @rpalmer-gsa -- Can this work?

## Reminder - please do the following before assigning reviewer

- [ ] update readme
- [ ] For frontend changes, ensure design review

And make sure that automated checks are ok

- fix houndci feedback
- ensure tests pass
- federalist builds
- no new SNYK vulnerabilities are introduced

### CODE REVIEW

**Comment by geekygirlsarah** [comment]
It reads fine to me, so I approve. 👍   But I'll wait for @LindsayYoung @JJediny @rpalmer-gsa to chime in before merging.

**Comment by pburkholder** [comment]
I've included cloud.gov in OKing the testing of sampleapp.app.cloud.gov because we're the only ones who can assure that the app owner actually is the app owner.

**Comment by JJediny** [comment]
LGTMerge

**Review by LindsayYoung — APPROVED** [review]
Thank you for your work on this

**Pull request merged**
