### PR TITLE
Join content revisions

### PR DESCRIPTION
**Pull request by coreycaitlin**
See issue(s) #1908 

[CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/join-revision)

[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/join-revision/)

/cc @kategarklavs @rooneywp

### CODE REVIEW

**Comment by gemfarmer** [comment]
Architecture work tracked here: #2335

**Comment by gemfarmer** [comment]
@coreycaitlin I think this is ready for you to give another work. I'm not completely content with how I left the lead, but it gives us more to gnaw on tomorrow 😺

**Comment by gemfarmer** [comment]
@awfrancisco Totally. I think that is even an issue: #2290

**Comment by awfrancisco** [comment]
How about that. We'll I'm good to go on this PR then.

**Comment by gemfarmer** [comment]
@awfrancisco I pushed the changes. Lemme know what you think!

cc @coreycaitlin

**Comment by awfrancisco** [comment]
When you click on Join 18F, the highlight moves to/remains on "how to apply". Is it possible to remove the highlight when you click join 18F so it's in the same state as when you initially load the page?

**Comment by gemfarmer** [comment]
For sure. Good catch. I didn't notice that.

**Comment by gemfarmer** [comment]
I can't remove the url hash without refreshing the page, which people generally don't like, but I can jump it to the top of the page without highlighting the top nav item!

**Comment by awfrancisco** [comment]
That's good with me

**Comment by gemfarmer** [comment]
The primary outstanding issue is what to put in the subnav header text? The position title seems a bit redundant, but I'm not sure what is better. `Position info`? 

screen shot 2017-03-01 at 2 57 30 pm

**Pull request merged**
