### PR TITLE
Integrate Kate's notes on db-subsetter, also add a colon

### PR DESCRIPTION
**Pull request by konklone**
I integrated @kategarklavs' edits in https://github.com/18F/18f.gsa.gov/pull/451#issuecomment-69217164, and added a colon before the list of commands.

### CODE REVIEW

**Comment by meiqimichelle** [comment]
@kategarklavs Did you want `–` (en-dash) for those dashes or the true ascii em-dash `&#8212;` ?

screenshot 2015-01-08 11 14 30

**Comment by kategarklavs** [comment]
The true em dash, please!

Also, not sure what the standard is re: spacing around em dashes. I tend to place a single space on either side of said dash (newspaper-style), though AP prescribes no spaces. Happy to follow the established convention.

**Comment by meiqimichelle** [comment]
We don't have a convention yet. I tend to follow Chicago style, so for me, no spaces. We will have to settle this via arm wrestling, clearly ;)

**Comment by waldoj** [comment]
AP (page 368) prescribes a full space before and after an em dash (as opposed to, e.g., a hair space), while Chicago (2.13), indeed, prescribes no space before and after. 18F will have to decide whether it's a Chicago or an AP shop, and presumably publish a house style guide for deviations from either norm. (Both are maddeningly antiquated in their treatment of technical language, so deviation is inevitable.)

**Comment by quepol** [comment]
full space before and after, please. :)

**Comment by waldoj** [comment]
you monster

**Comment by kategarklavs** [comment]
@meiqimichelle I personally prefer Chicago (no arm wrestling for me), but word on the street is that we tend to follow AP 'round these parts

**Comment by meiqimichelle** [comment]
I'm not sure if my keyboard will actually type a full space before and after an _em-dash_, but if @quepol says it can, I shall valiantly attempt! Editing PR now...

**Comment by meiqimichelle** [comment]
It now occurs to me -- are we doing AP ellipses, too, and their associated spaces? _goes off to search for the proper ascii ellipses code_

**Comment by gboone** [comment]
pro tip: `option + shift + -` will type an _em dash_, and `option + -` types an _en dash_

**Comment by gboone** [comment]
And `option + ;` for elipses `…`

**Comment by meiqimichelle** [comment]
@gboone I had it in my head that those don't always display cross-browser properly without the full ascii code, but I'm thinking this might be very old news at this point :) Perhaps I should learn the shortcuts now!

**Comment by konklone** [comment]
@gboone if you add OS X shortcuts for common characters to the readme or blogging guide, I'll add Ubuntu shortcuts. Deal??

**Comment by meiqimichelle** [comment]
I just added a bullet point that we're doing AP now. As for further tips, perhaps a separate section in the blogging guide for "Writing tips" or "Writing style tips" as the proto eventual house style guide.

**Comment by kategarklavs** [comment]
@meiqimichelle Sounds like a plan(!)

**Pull request merged**
