### PR TITLE
Dev --> master

### PR DESCRIPTION
**Pull request by gemfarmer**
[CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/dev)

[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/dev/)

Changes proposed in this pull request:
- adds an [About](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov//dev/about/) page that uses an up updated sticky nav
- updates project page layout #2246 
- adds a bunch of [new project pages](https://github.com/18F/18f.gsa.gov/issues/2283#issue-206649839):
  - [ ] [CALC](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/dev/what-we-deliver/calc/) - #2201 
  - [x] [Ready-2-Serve](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/dev/what-we-deliver/navy-ready-2-serve/) - #2248 
  - [x] [C2](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/dev/what-we-deliver/c2/) - #2202 
  - [x] [Agile BPA](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/dev/what-we-deliver/agile-bpa/) - #2250 
  - [x] [Federalist](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/dev/what-we-deliver/federalist/) - #2204 
  - [x] [DATA Act](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/dev/what-we-deliver/treasury-data-act/) - #2106 
  - [x] [eRegs](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/dev/what-we-deliver/eregulations/) - #2189 
  - [x] [myUSCIS](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/dev/what-we-deliver/dhs-myuscis/) - #2200 
- consolidates `profile-image` and `profile-intro` layouts #2268  

/cc @coreycaitlin @austinhernandez @elainekamlley @awfrancisco @kategarklavs @acolter @gboone

### CODE REVIEW

**Comment by gemfarmer** [comment]
@coreycaitlin it timed out, but all other checks have passed. Is there besides the build holding this up?

**Comment by coreycaitlin** [comment]
Just waiting on one more word from Alan, but I'll start reviewing carefully.

**Comment by coreycaitlin** [comment]
@gemfarmer It looks like some of our footer pages lost their titles in the great template merge of 2017:

screen shot 2017-02-15 at 11 12 19 am

**Comment by coreycaitlin** [comment]
@gemfarmer Also, in _extreme_ details, the spacing under `Open technology` is just _slightly_ tighter than it is under the other headers here. I think the culprit is a `last-of-type` situation.

screen shot 2017-02-15 at 11 15 34 am

**Comment by coreycaitlin** [comment]
Okay, I think this is good to go once we get the 👍 from @gboone. I'll also take a few moments tomorrow to review again.

**Pull request merged**
