### PR TITLE
Remove 18F vulnerability policy page, replace with GSA policy page

### PR DESCRIPTION
**Pull request by geekygirlsarah**
# Pull request summary

This removes the 18F-specific vulnerability policy and provides a link to GSA's policy instead.

Closes https://github.com/18F/delivery-assurance/issues/140

## Reminder - please do the following before assigning reviewer

- [X] update readme - N/A
- [X] For frontend changes, ensure design review - N/A

And make sure that automated checks are ok

- fix houndci feedback
- ensure tests pass
- federalist builds
- no new SNYK vulnerabilities are introdcued

### CODE REVIEW

**Comment by jameshochadel** [comment]
Thank you @geekygirlsarah! What do you think about leaving the current page up, but removing the content and leaving a note that links to the GSA page instead? That way existing links won't break and folks can find the new policy.

**Comment by geekygirlsarah** [comment]
I'd be fine putting the page back up with just the text "Our policy is now superceded by GSA's policy, available [here]" for backward compatibility. If @quarterback is also cool with it. (I know it's likely not visited, but having 404s isn't great and I found two blog posts that link to it.)

**Comment by jameshochadel** [comment]
Either a redirect or a page with an explanation makes sense to me — I'll leave it up to the experts 🙂

**Comment by geekygirlsarah** [comment]
I'm not sure how to do a redirect in Jekyll (aside from a hacky `<meta>` type redirect and I don't really want to go that route) so I figured a simple sentence with the new page would work.

**Pull request merged**
