### PR TITLE
tag change: health and human services to public benefits

### PR DESCRIPTION
**Pull request by iamjolly**
Signed-off-by: Robert Jolly <robert.jolly@gsa.gov>

# Pull request summary
Updates requested by the Public Benefits Portfolio team due to name change from Human Services Portfolio. This PR changes the tag "health and human services" to "public benefits" in the tests/schema/tags.yml and 14 posts. Replacing tag was preferred over adding a new tag at this time. 

cc/ @Dahianna for review and approval.

### CODE REVIEW

**Comment by iamjolly** [comment]
While this build is failing due to some Federalist/Ruby issue... @Dahianna, this was raised by @alexpandel in our chat related to the tag renaming:

> make sure we didn't inadvertently re-tag any posts that shouldn't have the PB tag... eg, I feel like I remember seeing some posts from PIFs about HHS work specifically, that may not be related to benefits directly

This impact one of the posts where we have renamed the tag in this PR. If needed, we can keep the HHS tag if a post is related to the Health and Human Services (Department) and not specifically tied to "public benefits."

**Comment by Dahianna** [comment]
I see that now. You can find all the posts with the `health and human services` tag here: https://18f.gsa.gov/tags/health-and-human-services/
Maybe we can update `health and human services` to `health and human services department` or `HHS`

**Comment by iamjolly** [comment]
Thanks @Dahianna 

I vote for `HHS` for the department tag simply due to the length advantage. I defer to others on this decision, though.

I'll ID the posts that need that and make new commit(s) within this PR before it gets merged. Will also change this PR to [WIP] so we don't make this live before it's ready.

**Comment by Dahianna** [comment]
Sounds good!


U.S. General Services Administration

*Dahianna V. Salazar Foreman*
 Digital Marketing
 TTS Outreach
 Technology Transformation Services
 Federal Acquisition Service
  <https://www.linkedin.com/company/gsa-tts/>  <https://twitter.com/GSA_TTS>

**Comment by iamjolly** [comment]
OK... the changes are in now and a [preview is built on Federalist](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.app.cloud.gov/preview/18f/18f.gsa.gov/hs-pb-tag-renaming/tags/public-benefits/) for your review/approval @Dahianna. Thank you!

**Comment by iamjolly** [comment]
@Dahianna - Are these tag changes OK to merge now?

**Comment by Dahianna** [comment]
Thanks for the reminder! Yep, they look good, I'll go ahead and merge

**Pull request merged**
