### PR TITLE
Removes api.data.gov

### PR DESCRIPTION
**Pull request by awfrancisco**
cc @wslack

### CODE REVIEW

**Comment by awfrancisco** [comment]
Please hold on merging

**Comment by cmc333333** [comment]
We still manage api.data.gov

**Comment by awfrancisco** [comment]
Yeah, this list isn't meant to be a comprehensive list of projects for each business unit, but rather examples of what we can sell to or do for agencies. The Product and Platforms list is platforms that agencies can take advantage of through IAAs, and it's my understanding (which might not be right) that we don't sell api.data.gov to other agencies, we simply manage it.

**Comment by wslack** [comment]
This can be closed; it should have been on my list.

**Pull request closed without merging**
