### PR TITLE
Agile workshop post

### PR DESCRIPTION
**Pull request by gboone**
Still needs:
- [x] excerpt
- [x] description (for open graph sharing)
- [x] inline images
- [x] open graph image
- [x] tags
- [x] `alt` text for images

### CODE REVIEW

**Comment by gboone** [comment]
Alt text for the images and we're good to roll this tomorrow morning. @RobertLRead @blacktm I'll have a demo link up in the morning so you can see it on a webpage

**Comment by gboone** [comment]
Alright, I think we're good to go. @RobertLRead and @blacktm You can preview the post here: https://ewpbrjapzl.localtunnel.me

**Comment by RobertLRead** [comment]
Thanks, Greg.

Teresa Gruber's nickname is spelled "Terri", not "Terrie".

I wrote it wrong at first, then I thought I corrected it, but my correction
must have gotten lost.

Can you correct?

On Wed, Feb 11, 2015 at 9:03 AM, Greg Boone <notifications@github.com>
wrote:

> Alright, I think we're good to go. @RobertLRead
> <https://github.com/RobertLRead> and @blacktm <https://github.com/blacktm>
> You can preview the post here: https://ewpbrjapzl.localtunnel.me
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/18f.gsa.gov/pull/519#issuecomment-73885156>.
>



-- 
Robert L. Read, PhD
Managing Director, 18F Consulting <http://18f.github.io/consulting/>
(202) 809-1941

**Comment by RobertLRead** [comment]
The alt text is not coming up as a hover for me in Chrome --- is it
supposed to?

On Wed, Feb 11, 2015 at 9:03 AM, Greg Boone <notifications@github.com>
wrote:

> Alright, I think we're good to go. @RobertLRead
> <https://github.com/RobertLRead> and @blacktm <https://github.com/blacktm>
> You can preview the post here: https://ewpbrjapzl.localtunnel.me
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/18f.gsa.gov/pull/519#issuecomment-73885156>.
>



-- 
Robert L. Read, PhD
Managing Director, 18F Consulting <http://18f.github.io/consulting/>
(202) 809-1941

**Comment by gboone** [comment]
I noticed that, too, I think it might be a Chrome thing. Screen readers should pick up on it, though.

**Comment by gboone** [comment]
Rollin' to staging

**Pull request merged**
