### PR TITLE
Update how-is-18F-funded.md

### PR DESCRIPTION
**Pull request by batemapf**
making this a bit more...simple.

### CODE REVIEW

**Comment by quepol** [comment]
I noticed you ratcheted our numbers back, Patrick. :)
Should we update them when it's actually May?

**Comment by batemapf** [comment]
screen shot 2016-04-29 at 1 53 33 pm

205 if you count PIF. we counting PIF?

**Comment by batemapf** [comment]
btw, i ratcheted your numbers _forward_. used to be 100, i bumped to 160. only forward, @quepol only forward.

**Comment by gboone** [comment]
Don't worry, your combined ratchetings conflicted with each other and I smoothed it all out in post.

**Comment by batemapf** [comment]
@gboone for the _smooooothing_ win!

**Pull request merged**
