### PR TITLE
Agencies list update

### PR DESCRIPTION
**Pull request by Dahianna**
**Do not merge until new design is implemented**

[CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/agencies-banner)

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/agencies-banner/)

[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/agencies-banner/README.md)

Changes proposed in this pull request:
- Update list
- Add new logos
-

Checklist:
- [ ] All images being added have been optimized **_--> [learn more](18f.gsa.gov/styleguide/images/#using-and-optimizing-jpg-and-png) about how to optimize images <--_**

### CODE REVIEW

**Comment by lsgitter** [comment]
@Dahianna can we mark this as done?

**Comment by Dahianna** [comment]
No, we’re still waiting for the changes to be implemented

**Comment by lsgitter** [comment]
@apburnes  will attempt to make this update.

**Comment by apburnes** [comment]
@Dahianna can we merge this so I can use the updated agencies in the homepage redesign?

**Comment by Dahianna** [comment]
Sure, I'll merge

**Pull request merged**
