### PR TITLE
New project landing page (what we deliver)

### PR DESCRIPTION
**Pull request by gemfarmer**
WIP WIP

Fixes issue(s) #2194 

[CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/project-home)

[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/project-home/)

Changes proposed in this pull request:
- Adds project homepage at `what-we-deliver`
- More to come

/cc @elainekamlley @coreycaitlin

### CODE REVIEW

**Comment by gemfarmer** [comment]
@coreycaitlin Do we still want to wait until next sprint to merge this? It's looking pretty good!

**Comment by coreycaitlin** [comment]
Okay! I think the biggest questions here are the text hierarchy at the top (do we need that second header? do we need some intro text under it? could we go straight to cards?), which could use some perspective from @austinhernandez:

screen shot 2017-02-16 at 11 33 30 am

And then at the bottom of the page, should the gray background be full-width?

**Comment by coreycaitlin** [comment]
Just resolved the conflicts 🎉 

@gemfarmer Maybe we can pair on this today and get it merged into dev?

**Comment by coreycaitlin** [comment]
LGTM! We can add placeholder images and tweak the past-partners list in a separate branch after we merge.

**Pull request merged**
