### PR TITLE
Add humans.txt

### PR DESCRIPTION
**Pull request by benbalter**
This pull request adds a simple `humans.txt` file. You can read more about the how and why of adding a `humans.txt` file over at [humanstxt.org](http://humanstxt.org/). TL;DR:

> It's an initiative for knowing the people behind a website. It's a TXT file that contains information about the different people who have contributed to building the website.

As an added bonus, it looks like this would be [the 2nd .gov with a `humans.txt` file](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#qscrl=1&q=site:.gov+inurl:humans.txt) after broadbandmap.gov (shoutout @feomike).

The humans.txt file is generated from `_data/team.json` (although technically it should be contributors to the site, perhaps via the GitHub API, not merely team members).

It looks like this:

```
/* TEAM */

Name: Jamie Albrecht
Handle: jamie
Working groups: Documentation and Hiring

Name: Sarah Allen
Handle: sarah
Working groups: Agile and Training and Education
Projects: midas
PIF Round: 2

Name: Shawn Allen
Handle: shawn
Working groups: Government user interface guidelines and Testing
Location: SFO
Projects: discovery, hourglass, and doi-extractives-data
Langauges: JavaScript, Python, HTML, CSS, and SQL

Name: jane avriette
Handle: jane
Working groups: Testing
```

and even [parses](https://github.com/benbalter/humans.rb):

```ruby
{:team=>
  [{:name=>"Jamie Albrecht", :handle=>"jamie", :"working groups"=>"Documentation and Hiring"},
   {:name=>"Sarah Allen", :handle=>"sarah", :"working groups"=>"Agile and Training and Education", :projects=>"midas", :"pif round"=>"2"},
   {:name=>"Shawn Allen",
    :handle=>"shawn",
    :"working groups"=>"Government user interface guidelines and Testing",
    :location=>"SFO",
    :projects=>"discovery, hourglass, and doi-extractives-data",
    :langauges=>"JavaScript, Python, HTML, CSS, and SQL"},
   {:name=>"jane avriette", :handle=>"jane", :"working groups"=>"Testing"},
   {:name=>"Leah Bannon", :handle=>"leah"},
   {:name=>"Moncef Belyamani", :handle=>"moncef", :"working groups"=>"Testing", :location=>"DCA"},
   {:name=>"David Best", :handle=>"david", :"working groups"=>"Testing", :location=>"DAY"},
   {:name=>"Tom Black", :handle=>"blacktm", :"working groups"=>"Documentation", :"pif round"=>"2"},
   {:name=>"Mike Bland", :handle=>"mbland", :"working groups"=>"Documentation, Testing, and Working Group", :location=>"DCA", :langauges=>"C++ and Python"},
   {:name=>"Greg Boone", :handle=>"boone", :location=>"DCA", :langauges=>"Python, Ruby, PHP, and JavaScript"},
   {:name=>"Nick Brethauer",
    :handle=>"brethauer",
    :"working groups"=>"Documentation, Training and Education, User Research, and Working Group",
    :projects=>"discovery and hourglass"},
   {:name=>"Nick Bristow", :handle=>"nick", :"working groups"=>"Accessibility and Working Group", :projects=>"doi-extractives-data"},
   {:name=>"Gray Brooks", :handle=>"gray", :"working groups"=>"Analytics and Working Group", :location=>"DCA", :projects=>"developer-program and api-data-gov"},
   {:name=>"Chris Cairns", :handle=>"chrisc", :projects=>"myra", :"pif round"=>"2"},
   {:name=>"Jeremy Canfield", :handle=>"jeremy", :"working groups"=>"User Research"}
 ]
}
```

You can see other examples in action at http://ben.balter.com/humans.txt (auto generated from the GitHub API) and https://github.com/humans.txt.

### CODE REVIEW

**Comment by konklone** [comment]
That's really cool, @benbalter! Thanks!

**Comment by meiqimichelle** [comment]
[USEITI](https://github.com/18F/doi-extractives-data) has a `humans.txt` ;) Just sayin'. Not automated, tho. I just keep it up to date with :heart: -- so this is spiffy!

**Comment by feomike** [comment]
:+1:

**Comment by gboone** [comment]
Really cool!

**Pull request merged**
