### PR TITLE
Content tests!

### PR DESCRIPTION
**Pull request by gboone**
We now test ever page generated in a build every time we issue a pull request. This has no effect on the presentation of 18f.gsa.gov, it's just to keep `production` up to date with `staging`.

### CODE REVIEW

**Comment by elainekamlley** [comment]
Whoo hoo!! Nice work @gboone :clap:

**Comment by gboone** [comment]
I'm OK ignoring Hound this time round. But I do fear the consequences of angering The Hound, generally.

**Comment by elainekamlley** [comment]
Cool! Merging, but he'll be watching: 
pasted image at 2015_10_16 03_58 pm

**Comment by cmc333333** [comment]
Great idea, @gboone !

**Pull request merged**
