### PR TITLE
Compress images

### PR DESCRIPTION
**Pull request by waldoj**
Fixes issue(s) #2301 .

[CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/compress-images/)

[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/compress-images/)

Changes proposed in this pull request:
- turn photo PNGs into JPEGs
- reduce U.S. flag PNG by 75%

/cc @ gboone

### CODE REVIEW

**Comment by coreycaitlin** [comment]
This also helps address #2223 🎉

**Comment by coreycaitlin** [comment]
I'm going to change the base branch to `dev` so we can roll this into the testing we're doing today.

**Comment by gemfarmer** [comment]
LGTM!

**Comment by gemfarmer** [comment]
It looks like the `image` frontmatter attribute in the following files need updating:

- _projects/doi-every-kid-in-a-park.md
- _projects/hhs-states.md

**Comment by gemfarmer** [comment]
@waldoj,  on a side note, do you have a preferred lossy compression app that you use? I have used ImageOptim, but I'm not sure if there is something better out there.

**Comment by waldoj** [comment]
> it looks like the file paths for the images haven't been updated after altering their file extensions (png --> jpg)

Argh—macOS' Finder told me that those weren't explicitly called anywhere. My bet is that Finder hadn't finished indexing the just-cloned repo, but didn't inform me of that fact. I'll fix that and update the PR.

> on a side note, do you have a preferred lossy compression app that you use? I have used ImageOptim, but I'm not sure if there is something better out there.

I'm still a strong ImageOptim advocate. :) But I always start with [ImageAlpha](https://pngmini.com/) to reduce the color palette and convert from PNG-24 to PNG-8 (when plausible). If there's a better GUI optimizer out there, I don't know about it...but I also haven't looked in a few years!

**Comment by gemfarmer** [comment]
Thanks @waldoj! And I just checked out ImageAlpha and it looks like it does provide a little more control. :1st_place_medal:

**Comment by gemfarmer** [comment]
Thanks @waldoj. I'm going to rebase and merge!

**Comment by gemfarmer** [comment]
@gboone @coreycaitlin I forgot that this was based off of master when I rebased, so the changes here reflect the changes in the Circle CI de-headaching PR (#2295) 😞 . This is a mistake, for sure, but I think it could be OK because `master` would benefit from all of the changes on this PR, namely:

- optimized images
- updated README and templates that include the correct preview link
- suspension of accesslint (no more ❌  on PRs to `master`)

I think this should be OK to merge. Sorry for commandeering  your PR, @waldoj !

**Pull request merged**
