### PR TITLE
Use Jina's correct name

### PR DESCRIPTION
**Pull request by maya**
# Pull request summary

(Optional) Closes #(issue_number).

## Reminder - please do the following before assigning reviewer

- [ ] update readme
- [ ] For frontend changes, ensure design review

And make sure that automated checks are ok

- fix houndci feedback
- ensure tests pass
- federalist builds
- no new SNYK vulnerabilities are introdcued

### CODE REVIEW

**Comment by geekygirlsarah** [comment]
Is the old name _wrong_ (like it was published incorrectly) or has it changed? (like marriage, name change, etc.) Or is there some other context for this update?

**Comment by abrouilette** [comment]
(Also hi, @maya!)

**Comment by maya** [comment]
@geekygirlsarah sure, she changed her name several years ago and [it's her preferred name](https://twitter.com/jina/status/938258031548153857) and what she goes by.

@abrouilette hi!

**Comment by geekygirlsarah** [comment]
> @geekygirlsarah sure, she changed her name several years ago and [it's her preferred name](https://twitter.com/jina/status/938258031548153857) and what she goes by.

Cool, thanks for pointing that out! Because it's a blog post and those have a more thorough review process, I'm double-checking there's no rule/reason why I couldn't merge this.

**Comment by abrouilette** [comment]
If you are comfortable with me greenlighting it, Sarah, consider the correction approved.

**Comment by geekygirlsarah** [comment]
With @abrouilette and @Dahianna both giving 👍 , I'll merge it!

Thanks for the update, @maya !

**Pull request merged**
