### PR TITLE
Blog post: We asked our coworkers: What have you learned from other 18F designers?

### PR DESCRIPTION
**Pull request by brentryanjohnson**
Adds blog post

## Title
We asked our coworkers: What have you learned from other 18F designers?

## Excerpt

18F is a learning organization. We continue learning from each other by regularly communicating, collaborating, and sharing our ideas (in video calls, in chat groups, everywhere we can) with teammates. 

In a recent design chapter meeting, our then-Design Director Anne Petersen asked: “What have you learned from others at 18F?” Here’s what our team of designers had to say.

### CODE REVIEW

**Comment by brentryanjohnson** [comment]
@erinzstrenio Please review the [🔍  preview](http://localhost:4000/2021/09/29/what-have-you-learned-from-other-18F-designers/)!

**Comment by brentryanjohnson** [comment]
This PR also includes a Sass update. The quote icon pseudo class was adding the icon for every child element, which meant it was printing multiple quote icons on top of each other. Thanks to @hbillings for helping to fix it!

**Comment by Dahianna** [comment]
Hi! Let me know when this blog post is ready to merge. I can post it on the week of 10/18

**Comment by brentryanjohnson** [comment]
@erinzstrenio Does the post look okay to you?

**Comment by geekygirlsarah** [comment]
Hey @brentryanjohnson @Dahianna @erinzstrenio!

I was reviewing old PRs... is this still being worked on? Do you want it merged in? (Or do you want it merged in with a more recent date?)

Thanks!

**Comment by annepetersen** [comment]
I'm pretty sure we still want to publish it. Looks like @erinzstrenio may still be working on a visual for it? I'll switch over to Slack to nudge: this may have gotten lost in holiday OOO emails and random Github notifications.

**Comment by geekygirlsarah** [comment]
> @geekygirlsarah Any chance you'd be available for a quick pairing to help me take this to the finish line? If so, I'll grab some time with you. (Thank you!!)

Yeah! Find a spot on my calendar and we can do it!

**Comment by erinzstrenio** [comment]
@brentryanjohnson Would you be up for taking another look at this (as another set of content eyes)? I think the only edit to make is move the second image down a bit in the post to break up the text a bit... maybe above the "on human-centered design" section? Otherwise I think it's in good shape. 

Oh, one other thing — should we give credit to Jia Gu for the images? Either in the caption or in a quick note at the bottom: "Special thanks to designer Jia Gu for the images!"

**Pull request merged**
