### PR TITLE
my first post

### PR DESCRIPTION
**Pull request by tomgrossdc**
Fixes issue(s) # .

[CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/BRANCH_NAME)

[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/BRANCH_NAME/)

[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/BRANCH_NAME/README.md)

Changes proposed in this pull request:
-
-
-

Checklist:
- [ ] All images being added have been optimized **_--> [learn more](18f.gsa.gov/styleguide/images/#using-and-optimizing-jpg-and-png) about how to optimize images <--_**

/cc @relevant-people

### CODE REVIEW

**Comment by tomgrossdc** [comment]
A new pull request has been created.

**Comment by awfrancisco** [comment]
Thanks for the pull request! I assume this came from following our [GitHub guide](https://18f.gsa.gov/2015/03/03/how-to-use-github-and-the-terminal-a-guide/). If you're interested in making other contributions to 18F repositories or learning more about open source, you can join one of our public Slack channels [here](https://chat.18f.gov/).

**Comment by tomgrossdc** [comment]
Thanks,
I was following your guide which was referred to me by codefordc.org
Thanks for your instructions, I learned a lot.
tom

Thomas F Gross

home: 1616 Q St NW Apt E
Washington DC,
202 277 0443
Email:  tgrossdc@gmail.com <tommyerols@gmail.com>

Any jackass can kick down a barn, but it takes a good carpenter to build
one. Sam Rayburn

**Comment by awfrancisco** [comment]
@tomgrossdc Heads up that your email signature, including your contact information, appears in the public comment thread on this pull request. You can edit your comment on GitHub to remove your contact information if you don't want it to be public. Just head to GitHub and click the little pencil icon in the corner of your comment to edit it.

**Comment by tomgrossdc** [comment]
Thanks, I finally found the comment and edited it.
I guess most people go to the github to respond to comments, instead of from their email accounts.
Tom

**Pull request closed without merging**
